export type Slot = "breakfast" | "lunch" | "dinner";
export type IngredientCategory =
  | "veg"
  | "grain"
  | "dairy"
  | "legume"
  | "spice"
  | "oil"
  | "fruit"
  | "nut"
  | "other";

export interface Ingredient {
  name: string;
  qty: number;
  unit: "g" | "ml" | "pc";
  category: IngredientCategory;
}

export type Cuisine =
  | "north-indian"
  | "south-indian"
  | "gujarati"
  | "punjabi"
  | "bengali"
  | "maharashtrian"
  | "indo-chinese"
  | "continental";

export type CookingType =
  | "stovetop"
  | "no-cook"
  | "steamed"
  | "baked"
  | "fried"
  | "grilled"
  | "instant-pot";

export type Equipment =
  | "stove"
  | "oven"
  | "airfryer"
  | "microwave"
  | "blender"
  | "pressure-cooker"
  | "griddle";

export interface Dish {
  id: string;
  name: string;
  emoji: string;
  slots: Slot[];
  kcal: number;
  protein: number; // g
  carbs: number; // g
  fat: number; // g
  tags: DishTag[];
  ingredients: Ingredient[];
  cuisine?: Cuisine;
  cookingType?: CookingType;
  equipment?: Equipment[];
  prepMinutes?: number;
  spiceLevel?: 0 | 1 | 2 | 3;
  recipeUrl?: string;
}

export type DishTag =
  | "pizza"
  | "paratha"
  | "fried-breakfast"
  | "dal"
  | "legume"
  | "leafy"
  | "sweet"
  | "light";

export const CATEGORY_EMOJI: Record<IngredientCategory, string> = {
  veg: "🥬",
  grain: "🌾",
  dairy: "🥛",
  legume: "🫘",
  spice: "🧂",
  oil: "🫒",
  fruit: "🍎",
  nut: "🥜",
  other: "🧺",
};

export function youtubeSearchUrl(name: string): string {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(name + " recipe")}`;
}

export const DISHES: Dish[] = [
  {
    id: "l1",
    name: "Achari Paneer + Roti",
    emoji: "🧀",
    slots: ["lunch"],
    kcal: 610,
    protein: 24,
    carbs: 56,
    fat: 28,
    tags: ["light"],
    ingredients: [{"name":"paneer","qty":100,"unit":"g","category":"dairy"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"achari masala","qty":10,"unit":"g","category":"spice"},{"name":"oil","qty":12,"unit":"ml","category":"oil"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Achari Paneer + Roti")
  },
  {
    id: "d1",
    name: "Air Fryer Manchurian + Noodles",
    emoji: "🥡",
    slots: ["dinner"],
    kcal: 590,
    protein: 14,
    carbs: 80,
    fat: 20,
    tags: ["light"],
    ingredients: [{"name":"noodles","qty":80,"unit":"g","category":"grain"},{"name":"mixed veg","qty":120,"unit":"g","category":"veg"},{"name":"oil","qty":12,"unit":"ml","category":"oil"}],
    cuisine: "indo-chinese",
    cookingType: "baked",
    equipment: ["airfryer","stove"],
    prepMinutes: 40,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Air Fryer Manchurian + Noodles")
  },
  {
    id: "d2",
    name: "Air Fryer Protein Cutlets",
    emoji: "🧆",
    slots: ["dinner"],
    kcal: 380,
    protein: 18,
    carbs: 45,
    fat: 12,
    tags: ["light","legume"],
    ingredients: [{"name":"paneer","qty":50,"unit":"g","category":"dairy"},{"name":"soya granules","qty":30,"unit":"g","category":"legume"},{"name":"potato","qty":50,"unit":"g","category":"veg"},{"name":"breadcrumbs","qty":20,"unit":"g","category":"grain"}],
    cuisine: "continental",
    cookingType: "baked",
    equipment: ["airfryer"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Air Fryer Protein Cutlets")
  },
  {
    id: "d3",
    name: "Air Fryer Spring Rolls & Nuggets",
    emoji: "🍟",
    slots: ["dinner"],
    kcal: 440,
    protein: 12,
    carbs: 55,
    fat: 16,
    tags: ["light"],
    ingredients: [{"name":"frozen spring rolls & nuggets","qty":150,"unit":"g","category":"other"},{"name":"oil spray","qty":5,"unit":"ml","category":"oil"}],
    cuisine: "indo-chinese",
    cookingType: "baked",
    equipment: ["airfryer"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Air Fryer Spring Rolls & Nuggets")
  },
  {
    id: "l2",
    name: "Aloo Gobi + Roti",
    emoji: "🥔",
    slots: ["lunch"],
    kcal: 520,
    protein: 14,
    carbs: 70,
    fat: 18,
    tags: ["light"],
    ingredients: [{"name":"potato","qty":120,"unit":"g","category":"veg"},{"name":"cauliflower","qty":120,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":12,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Aloo Gobi + Roti")
  },
  {
    id: "l3",
    name: "Aloo Paratha",
    emoji: "🫓",
    slots: ["lunch"],
    kcal: 480,
    protein: 11,
    carbs: 60,
    fat: 20,
    tags: ["paratha"],
    ingredients: [{"name":"wheat flour","qty":80,"unit":"g","category":"grain"},{"name":"potato","qty":120,"unit":"g","category":"veg"},{"name":"ghee","qty":15,"unit":"g","category":"dairy"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Aloo Paratha")
  },
  {
    id: "l4",
    name: "Aloo Sabzi + Roti",
    emoji: "🥔",
    slots: ["lunch"],
    kcal: 480,
    protein: 10,
    carbs: 65,
    fat: 16,
    tags: ["light"],
    ingredients: [{"name":"potato","qty":150,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Aloo Sabzi + Roti")
  },
  {
    id: "d4",
    name: "Arrabbiata Pasta",
    emoji: "🍝",
    slots: ["dinner"],
    kcal: 510,
    protein: 14,
    carbs: 78,
    fat: 12,
    tags: ["light"],
    ingredients: [{"name":"pasta","qty":100,"unit":"g","category":"grain"},{"name":"tomato pureee","qty":100,"unit":"g","category":"veg"},{"name":"chilli flakes & herbs","qty":5,"unit":"g","category":"spice"},{"name":"olive oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Arrabbiata Pasta")
  },
  {
    id: "b1",
    name: "Banana + Whey Shake",
    emoji: "🥤",
    slots: ["breakfast"],
    kcal: 320,
    protein: 28,
    carbs: 40,
    fat: 5,
    tags: ["light"],
    ingredients: [{"name":"whey protein","qty":30,"unit":"g","category":"other"},{"name":"banana","qty":1,"unit":"pc","category":"fruit"},{"name":"peanut butter","qty":15,"unit":"g","category":"nut"},{"name":"milk","qty":200,"unit":"ml","category":"dairy"}],
    cuisine: "continental",
    cookingType: "no-cook",
    equipment: ["blender"],
    prepMinutes: 5,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Banana + Whey Shake")
  },
  {
    id: "d5",
    name: "Besan Chilla",
    emoji: "🥞",
    slots: ["dinner"],
    kcal: 320,
    protein: 15,
    carbs: 32,
    fat: 12,
    tags: ["legume","light"],
    ingredients: [{"name":"gram flour","qty":70,"unit":"g","category":"legume"},{"name":"onion","qty":40,"unit":"g","category":"veg"},{"name":"tomato","qty":40,"unit":"g","category":"veg"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Besan Chilla")
  },
  {
    id: "l5",
    name: "Black Chana + Roti",
    emoji: "🫘",
    slots: ["lunch"],
    kcal: 530,
    protein: 19,
    carbs: 72,
    fat: 12,
    tags: ["legume"],
    ingredients: [{"name":"black chickpeas","qty":80,"unit":"g","category":"legume"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"onion","qty":40,"unit":"g","category":"veg"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove","pressure-cooker"],
    prepMinutes: 40,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Black Chana + Roti")
  },
  {
    id: "d6",
    name: "Broccoli Almond Soup + Caesar-style Salad",
    emoji: "🥗",
    slots: ["dinner"],
    kcal: 340,
    protein: 10,
    carbs: 32,
    fat: 16,
    tags: ["light"],
    ingredients: [{"name":"broccoli","qty":150,"unit":"g","category":"veg"},{"name":"almonds","qty":20,"unit":"g","category":"nut"},{"name":"salad leaves","qty":100,"unit":"g","category":"veg"},{"name":"olive oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove","blender"],
    prepMinutes: 25,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Broccoli Almond Soup + Caesar-style Salad")
  },
  {
    id: "l6",
    name: "Chole + Rice",
    emoji: "🍛",
    slots: ["lunch"],
    kcal: 610,
    protein: 21,
    carbs: 92,
    fat: 14,
    tags: ["legume"],
    ingredients: [{"name":"chickpeas","qty":90,"unit":"g","category":"legume"},{"name":"rice","qty":100,"unit":"g","category":"grain"},{"name":"onion","qty":60,"unit":"g","category":"veg"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "punjabi",
    cookingType: "instant-pot",
    equipment: ["pressure-cooker"],
    prepMinutes: 40,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Chole + Rice")
  },
  {
    id: "l7",
    name: "Chole Bhature/Kulche",
    emoji: "🫓",
    slots: ["lunch"],
    kcal: 650,
    protein: 18,
    carbs: 82,
    fat: 28,
    tags: ["fried-breakfast","legume"],
    ingredients: [{"name":"chickpeas","qty":80,"unit":"g","category":"legume"},{"name":"maida","qty":90,"unit":"g","category":"grain"},{"name":"oil","qty":30,"unit":"ml","category":"oil"},{"name":"onion","qty":40,"unit":"g","category":"veg"}],
    cuisine: "punjabi",
    cookingType: "fried",
    equipment: ["stove"],
    prepMinutes: 60,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Chole Bhature/Kulche")
  },
  {
    id: "b2",
    name: "Curd + Fruits",
    emoji: "🍏",
    slots: ["breakfast"],
    kcal: 210,
    protein: 8,
    carbs: 32,
    fat: 5,
    tags: ["light"],
    ingredients: [{"name":"curd","qty":150,"unit":"g","category":"dairy"},{"name":"apple","qty":1,"unit":"pc","category":"fruit"},{"name":"pomegranate seeds","qty":50,"unit":"g","category":"fruit"},{"name":"honey","qty":10,"unit":"g","category":"other"}],
    cuisine: "north-indian",
    cookingType: "no-cook",
    equipment: [],
    prepMinutes: 5,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Curd + Fruits")
  },
  {
    id: "l8",
    name: "Dal Baati",
    emoji: "🫓",
    slots: ["lunch"],
    kcal: 680,
    protein: 20,
    carbs: 85,
    fat: 26,
    tags: ["dal","legume"],
    ingredients: [{"name":"wheat flour","qty":100,"unit":"g","category":"grain"},{"name":"mixed dal","qty":60,"unit":"g","category":"legume"},{"name":"ghee","qty":25,"unit":"g","category":"dairy"}],
    cuisine: "gujarati",
    cookingType: "baked",
    equipment: ["oven","stove"],
    prepMinutes: 60,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Dal Baati")
  },
  {
    id: "d7",
    name: "Dal Dhokli",
    emoji: "🍲",
    slots: ["dinner"],
    kcal: 480,
    protein: 18,
    carbs: 70,
    fat: 12,
    tags: ["dal","legume","light"],
    ingredients: [{"name":"toor dal","qty":60,"unit":"g","category":"legume"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"ghee","qty":10,"unit":"g","category":"dairy"}],
    cuisine: "gujarati",
    cookingType: "stovetop",
    equipment: ["pressure-cooker"],
    prepMinutes: 45,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Dal Dhokli")
  },
  {
    id: "l9",
    name: "Dal Palak + Rice",
    emoji: "🍛",
    slots: ["lunch"],
    kcal: 520,
    protein: 19,
    carbs: 80,
    fat: 10,
    tags: ["dal","legume","leafy"],
    ingredients: [{"name":"toor dal","qty":70,"unit":"g","category":"legume"},{"name":"spinach","qty":100,"unit":"g","category":"veg"},{"name":"rice","qty":100,"unit":"g","category":"grain"},{"name":"oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove","pressure-cooker"],
    prepMinutes: 35,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Dal Palak + Rice")
  },
  {
    id: "b3",
    name: "Fruit + Whey",
    emoji: "🍌",
    slots: ["breakfast"],
    kcal: 260,
    protein: 26,
    carbs: 30,
    fat: 3,
    tags: ["light"],
    ingredients: [{"name":"whey protein","qty":30,"unit":"g","category":"other"},{"name":"banana","qty":1,"unit":"pc","category":"fruit"},{"name":"milk","qty":150,"unit":"ml","category":"dairy"}],
    cuisine: "continental",
    cookingType: "no-cook",
    equipment: ["blender"],
    prepMinutes: 5,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Fruit + Whey")
  },
  {
    id: "b4",
    name: "Fruit Bowl",
    emoji: "🥣",
    slots: ["breakfast"],
    kcal: 180,
    protein: 3,
    carbs: 42,
    fat: 1,
    tags: ["light"],
    ingredients: [{"name":"papaya","qty":100,"unit":"g","category":"fruit"},{"name":"apple","qty":1,"unit":"pc","category":"fruit"},{"name":"banana","qty":1,"unit":"pc","category":"fruit"},{"name":"pomegranate seeds","qty":50,"unit":"g","category":"fruit"}],
    cuisine: "continental",
    cookingType: "no-cook",
    equipment: [],
    prepMinutes: 5,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Fruit Bowl")
  },
  {
    id: "d8",
    name: "Garlic Bread + Light Soup Blend",
    emoji: "🍞",
    slots: ["dinner"],
    kcal: 390,
    protein: 11,
    carbs: 54,
    fat: 13,
    tags: ["light"],
    ingredients: [{"name":"bread","qty":80,"unit":"g","category":"grain"},{"name":"mixed soup veg","qty":150,"unit":"g","category":"veg"},{"name":"butter & garlic","qty":15,"unit":"g","category":"dairy"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Garlic Bread + Light Soup Blend")
  },
  {
    id: "l10",
    name: "Gobi Matar + Roti",
    emoji: "🥦",
    slots: ["lunch"],
    kcal: 480,
    protein: 12,
    carbs: 64,
    fat: 15,
    tags: ["light"],
    ingredients: [{"name":"cauliflower","qty":120,"unit":"g","category":"veg"},{"name":"peas","qty":80,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Gobi Matar + Roti")
  },
  {
    id: "l11",
    name: "Gobi Paratha",
    emoji: "🫓",
    slots: ["lunch"],
    kcal: 460,
    protein: 12,
    carbs: 58,
    fat: 19,
    tags: ["paratha"],
    ingredients: [{"name":"wheat flour","qty":80,"unit":"g","category":"grain"},{"name":"cauliflower","qty":120,"unit":"g","category":"veg"},{"name":"ghee","qty":15,"unit":"g","category":"dairy"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Gobi Paratha")
  },
  {
    id: "b5",
    name: "Greek Yogurt + Fruits",
    emoji: "🍓",
    slots: ["breakfast"],
    kcal: 220,
    protein: 15,
    carbs: 28,
    fat: 4,
    tags: ["light"],
    ingredients: [{"name":"greek yogurt","qty":150,"unit":"g","category":"dairy"},{"name":"mixed berries","qty":80,"unit":"g","category":"fruit"},{"name":"honey","qty":10,"unit":"g","category":"other"}],
    cuisine: "continental",
    cookingType: "no-cook",
    equipment: [],
    prepMinutes: 5,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Greek Yogurt + Fruits")
  },
  {
    id: "d9",
    name: "Handvo",
    emoji: "🥮",
    slots: ["dinner"],
    kcal: 410,
    protein: 14,
    carbs: 62,
    fat: 10,
    tags: ["legume","light"],
    ingredients: [{"name":"rice & lentil batter","qty":150,"unit":"g","category":"grain"},{"name":"bottle gourd","qty":50,"unit":"g","category":"veg"},{"name":"oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "gujarati",
    cookingType: "baked",
    equipment: ["oven","stove"],
    prepMinutes: 45,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Handvo")
  },
  {
    id: "d10",
    name: "High Protein Red Sauce Pasta",
    emoji: "🍝",
    slots: ["dinner"],
    kcal: 580,
    protein: 28,
    carbs: 75,
    fat: 14,
    tags: ["legume"],
    ingredients: [{"name":"chickpea pasta","qty":100,"unit":"g","category":"grain"},{"name":"tomato sauce","qty":100,"unit":"g","category":"veg"},{"name":"cheese","qty":20,"unit":"g","category":"dairy"},{"name":"oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("High Protein Red Sauce Pasta")
  },
  {
    id: "l12",
    name: "Kadai Paneer + Roti",
    emoji: "🌶️",
    slots: ["lunch"],
    kcal: 640,
    protein: 26,
    carbs: 58,
    fat: 32,
    tags: ["light"],
    ingredients: [{"name":"paneer","qty":120,"unit":"g","category":"dairy"},{"name":"capsicum","qty":80,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"onion","qty":50,"unit":"g","category":"veg"},{"name":"oil","qty":15,"unit":"ml","category":"oil"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Kadai Paneer + Roti")
  },
  {
    id: "d11",
    name: "Light Dahi Sandwich",
    emoji: "🥪",
    slots: ["dinner"],
    kcal: 340,
    protein: 12,
    carbs: 45,
    fat: 11,
    tags: ["light"],
    ingredients: [{"name":"bread","qty":80,"unit":"g","category":"grain"},{"name":"hung curd","qty":60,"unit":"g","category":"dairy"},{"name":"cucumber","qty":30,"unit":"g","category":"veg"},{"name":"butter","qty":5,"unit":"g","category":"dairy"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 15,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Light Dahi Sandwich")
  },
  {
    id: "l13",
    name: "Methi Aloo + Roti",
    emoji: "🥔",
    slots: ["lunch"],
    kcal: 480,
    protein: 12,
    carbs: 64,
    fat: 15,
    tags: ["leafy"],
    ingredients: [{"name":"fenugreek leaves","qty":100,"unit":"g","category":"veg"},{"name":"potato","qty":100,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Methi Aloo + Roti")
  },
  {
    id: "l14",
    name: "Methi Malai Paneer + Roti",
    emoji: "🥬",
    slots: ["lunch"],
    kcal: 630,
    protein: 25,
    carbs: 54,
    fat: 32,
    tags: ["leafy"],
    ingredients: [{"name":"paneer","qty":100,"unit":"g","category":"dairy"},{"name":"fenugreek leaves","qty":80,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"cream","qty":20,"unit":"ml","category":"dairy"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Methi Malai Paneer + Roti")
  },
  {
    id: "l15",
    name: "Mix Veg Curry + Roti",
    emoji: "🥕",
    slots: ["lunch"],
    kcal: 520,
    protein: 14,
    carbs: 66,
    fat: 20,
    tags: ["light"],
    ingredients: [{"name":"mixed veg","qty":200,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":12,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Mix Veg Curry + Roti")
  },
  {
    id: "d12",
    name: "Moong Dal Chilla",
    emoji: "🥞",
    slots: ["dinner"],
    kcal: 340,
    protein: 16,
    carbs: 45,
    fat: 8,
    tags: ["legume","light"],
    ingredients: [{"name":"moong dal","qty":80,"unit":"g","category":"legume"},{"name":"ginger","qty":5,"unit":"g","category":"spice"},{"name":"oil","qty":6,"unit":"ml","category":"oil"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Moong Dal Chilla")
  },
  {
    id: "d13",
    name: "Moong Dal Khichdi",
    emoji: "🍲",
    slots: ["dinner"],
    kcal: 440,
    protein: 16,
    carbs: 68,
    fat: 8,
    tags: ["dal","legume","light"],
    ingredients: [{"name":"rice","qty":60,"unit":"g","category":"grain"},{"name":"moong dal","qty":60,"unit":"g","category":"legume"},{"name":"ghee","qty":8,"unit":"g","category":"dairy"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["pressure-cooker"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Moong Dal Khichdi")
  },
  {
    id: "d14",
    name: "Moong Dal Khichdi + Kadhi",
    emoji: "🍛",
    slots: ["dinner"],
    kcal: 490,
    protein: 16,
    carbs: 72,
    fat: 12,
    tags: ["dal","legume","light"],
    ingredients: [{"name":"rice","qty":50,"unit":"g","category":"grain"},{"name":"moong dal","qty":50,"unit":"g","category":"legume"},{"name":"yogurt","qty":80,"unit":"g","category":"dairy"},{"name":"ghee","qty":8,"unit":"g","category":"dairy"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["pressure-cooker"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Moong Dal Khichdi + Kadhi")
  },
  {
    id: "l16",
    name: "Mushroom Masala + Roti",
    emoji: "🍄",
    slots: ["lunch"],
    kcal: 490,
    protein: 15,
    carbs: 60,
    fat: 16,
    tags: ["light"],
    ingredients: [{"name":"mushrooms","qty":150,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"onion","qty":50,"unit":"g","category":"veg"},{"name":"tomato","qty":50,"unit":"g","category":"veg"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Mushroom Masala + Roti")
  },
  {
    id: "d15",
    name: "Mushroom Pizza",
    emoji: "🍕",
    slots: ["dinner"],
    kcal: 710,
    protein: 20,
    carbs: 82,
    fat: 26,
    tags: ["pizza"],
    ingredients: [{"name":"pizza base","qty":150,"unit":"g","category":"grain"},{"name":"mushrooms","qty":100,"unit":"g","category":"veg"},{"name":"cheese","qty":60,"unit":"g","category":"dairy"},{"name":"tomato sauce","qty":40,"unit":"g","category":"veg"}],
    cuisine: "continental",
    cookingType: "baked",
    equipment: ["oven"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Mushroom Pizza")
  },
  {
    id: "l17",
    name: "Mushroom Pulao",
    emoji: "🍄",
    slots: ["lunch"],
    kcal: 500,
    protein: 11,
    carbs: 85,
    fat: 10,
    tags: ["light"],
    ingredients: [{"name":"mushrooms","qty":150,"unit":"g","category":"veg"},{"name":"basmati rice","qty":100,"unit":"g","category":"grain"},{"name":"oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Mushroom Pulao")
  },
  {
    id: "d16",
    name: "Mushroom Sandwich",
    emoji: "🥪",
    slots: ["dinner"],
    kcal: 400,
    protein: 12,
    carbs: 50,
    fat: 14,
    tags: ["light"],
    ingredients: [{"name":"bread","qty":80,"unit":"g","category":"grain"},{"name":"mushrooms","qty":100,"unit":"g","category":"veg"},{"name":"cheese","qty":20,"unit":"g","category":"dairy"},{"name":"butter","qty":5,"unit":"g","category":"dairy"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Mushroom Sandwich")
  },
  {
    id: "d17",
    name: "Mushroom Soup + Garden Salad",
    emoji: "🥗",
    slots: ["dinner"],
    kcal: 320,
    protein: 9,
    carbs: 38,
    fat: 12,
    tags: ["light"],
    ingredients: [{"name":"mushrooms","qty":150,"unit":"g","category":"veg"},{"name":"salad leaves","qty":100,"unit":"g","category":"veg"},{"name":"cream","qty":15,"unit":"ml","category":"dairy"},{"name":"olive oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove","blender"],
    prepMinutes: 25,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Mushroom Soup + Garden Salad")
  },
  {
    id: "b6",
    name: "Overnight Oats",
    emoji: "🥣",
    slots: ["breakfast"],
    kcal: 350,
    protein: 12,
    carbs: 55,
    fat: 8,
    tags: ["light"],
    ingredients: [{"name":"oats","qty":50,"unit":"g","category":"grain"},{"name":"milk","qty":150,"unit":"ml","category":"dairy"},{"name":"chia seeds","qty":10,"unit":"g","category":"nut"},{"name":"honey","qty":10,"unit":"g","category":"other"},{"name":"banana","qty":1,"unit":"pc","category":"fruit"}],
    cuisine: "continental",
    cookingType: "no-cook",
    equipment: [],
    prepMinutes: 5,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Overnight Oats")
  },
  {
    id: "l18",
    name: "Palak Paneer + Roti",
    emoji: "🥬",
    slots: ["lunch"],
    kcal: 620,
    protein: 28,
    carbs: 55,
    fat: 28,
    tags: ["leafy"],
    ingredients: [{"name":"paneer","qty":120,"unit":"g","category":"dairy"},{"name":"spinach","qty":150,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":12,"unit":"ml","category":"oil"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["stove","blender"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Palak Paneer + Roti")
  },
  {
    id: "l19",
    name: "Paneer Bhurji + Roti",
    emoji: "🧀",
    slots: ["lunch"],
    kcal: 560,
    protein: 26,
    carbs: 50,
    fat: 28,
    tags: ["light"],
    ingredients: [{"name":"paneer","qty":120,"unit":"g","category":"dairy"},{"name":"onion","qty":50,"unit":"g","category":"veg"},{"name":"tomato","qty":50,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"ghee","qty":10,"unit":"g","category":"dairy"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Paneer Bhurji + Roti")
  },
  {
    id: "l20",
    name: "Paneer Paratha",
    emoji: "🫓",
    slots: ["dinner","lunch"],
    kcal: 520,
    protein: 18,
    carbs: 58,
    fat: 22,
    tags: ["paratha"],
    ingredients: [{"name":"wheat flour","qty":70,"unit":"g","category":"grain"},{"name":"paneer","qty":60,"unit":"g","category":"dairy"},{"name":"ghee","qty":12,"unit":"g","category":"dairy"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Paneer Paratha")
  },
  {
    id: "l21",
    name: "Paneer Pulao",
    emoji: "🍚",
    slots: ["lunch"],
    kcal: 580,
    protein: 20,
    carbs: 80,
    fat: 18,
    tags: ["light"],
    ingredients: [{"name":"paneer","qty":80,"unit":"g","category":"dairy"},{"name":"basmati rice","qty":100,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Paneer Pulao")
  },
  {
    id: "l22",
    name: "Paneer Tikka + Roti",
    emoji: "🧀",
    slots: ["lunch"],
    kcal: 610,
    protein: 26,
    carbs: 50,
    fat: 28,
    tags: ["light"],
    ingredients: [{"name":"paneer","qty":120,"unit":"g","category":"dairy"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"yogurt","qty":40,"unit":"g","category":"dairy"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "punjabi",
    cookingType: "grilled",
    equipment: ["griddle"],
    prepMinutes: 35,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Paneer Tikka + Roti")
  },
  {
    id: "l23",
    name: "Paneer Tikka Masala + Roti",
    emoji: "🧀",
    slots: ["lunch"],
    kcal: 630,
    protein: 26,
    carbs: 54,
    fat: 30,
    tags: ["light"],
    ingredients: [{"name":"paneer","qty":100,"unit":"g","category":"dairy"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"yogurt","qty":50,"unit":"g","category":"dairy"},{"name":"oil","qty":12,"unit":"ml","category":"oil"}],
    cuisine: "punjabi",
    cookingType: "grilled",
    equipment: ["stove","griddle"],
    prepMinutes: 40,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Paneer Tikka Masala + Roti")
  },
  {
    id: "d18",
    name: "Paneer Tikka Pizza",
    emoji: "🍕",
    slots: ["dinner"],
    kcal: 740,
    protein: 26,
    carbs: 82,
    fat: 30,
    tags: ["pizza"],
    ingredients: [{"name":"pizza base","qty":150,"unit":"g","category":"grain"},{"name":"paneer","qty":60,"unit":"g","category":"dairy"},{"name":"cheese","qty":60,"unit":"g","category":"dairy"},{"name":"tomato sauce","qty":40,"unit":"g","category":"veg"}],
    cuisine: "continental",
    cookingType: "baked",
    equipment: ["oven"],
    prepMinutes: 35,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Paneer Tikka Pizza")
  },
  {
    id: "l24",
    name: "Pav Bhaji",
    emoji: "🍞",
    slots: ["lunch"],
    kcal: 600,
    protein: 14,
    carbs: 80,
    fat: 22,
    tags: ["light"],
    ingredients: [{"name":"pav bread","qty":100,"unit":"g","category":"grain"},{"name":"mixed veg","qty":200,"unit":"g","category":"veg"},{"name":"butter","qty":20,"unit":"g","category":"dairy"}],
    cuisine: "maharashtrian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 40,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Pav Bhaji")
  },
  {
    id: "l25",
    name: "Podi Idli",
    emoji: "⚪",
    slots: ["lunch"],
    kcal: 400,
    protein: 11,
    carbs: 68,
    fat: 8,
    tags: ["legume"],
    ingredients: [{"name":"idli batter","qty":150,"unit":"g","category":"grain"},{"name":"podi powder","qty":15,"unit":"g","category":"spice"},{"name":"ghee","qty":8,"unit":"g","category":"dairy"}],
    cuisine: "south-indian",
    cookingType: "steamed",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Podi Idli")
  },
  {
    id: "l26",
    name: "Pyaz Paratha",
    emoji: "🫓",
    slots: ["lunch"],
    kcal: 460,
    protein: 10,
    carbs: 58,
    fat: 18,
    tags: ["paratha"],
    ingredients: [{"name":"wheat flour","qty":80,"unit":"g","category":"grain"},{"name":"onion","qty":100,"unit":"g","category":"veg"},{"name":"ghee","qty":12,"unit":"g","category":"dairy"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Pyaz Paratha")
  },
  {
    id: "l27",
    name: "Rajma + Rice",
    emoji: "🍛",
    slots: ["lunch"],
    kcal: 620,
    protein: 22,
    carbs: 95,
    fat: 14,
    tags: ["legume"],
    ingredients: [{"name":"kidney beans","qty":90,"unit":"g","category":"legume"},{"name":"rice","qty":100,"unit":"g","category":"grain"},{"name":"onion","qty":60,"unit":"g","category":"veg"},{"name":"tomato","qty":60,"unit":"g","category":"veg"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "punjabi",
    cookingType: "instant-pot",
    equipment: ["pressure-cooker"],
    prepMinutes: 45,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Rajma + Rice")
  },
  {
    id: "d19",
    name: "Roti + Aloo Matar",
    emoji: "🍲",
    slots: ["dinner"],
    kcal: 460,
    protein: 11,
    carbs: 62,
    fat: 13,
    tags: ["light"],
    ingredients: [{"name":"potato","qty":100,"unit":"g","category":"veg"},{"name":"peas","qty":80,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Roti + Aloo Matar")
  },
  {
    id: "d20",
    name: "Roti + Baingan Bharta",
    emoji: "🍆",
    slots: ["dinner"],
    kcal: 450,
    protein: 11,
    carbs: 56,
    fat: 16,
    tags: ["light"],
    ingredients: [{"name":"eggplant","qty":200,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Roti + Baingan Bharta")
  },
  {
    id: "d21",
    name: "Roti + Bharwa Bhindi",
    emoji: "🌿",
    slots: ["dinner"],
    kcal: 430,
    protein: 10,
    carbs: 54,
    fat: 14,
    tags: ["light"],
    ingredients: [{"name":"okra","qty":120,"unit":"g","category":"veg"},{"name":"spices","qty":15,"unit":"g","category":"spice"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Roti + Bharwa Bhindi")
  },
  {
    id: "d22",
    name: "Roti + Bhindi Masala",
    emoji: "🌿",
    slots: ["dinner"],
    kcal: 440,
    protein: 11,
    carbs: 58,
    fat: 14,
    tags: ["light"],
    ingredients: [{"name":"okra","qty":120,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Roti + Bhindi Masala")
  },
  {
    id: "d23",
    name: "Roti + Capsicum Masala",
    emoji: "🫑",
    slots: ["dinner"],
    kcal: 430,
    protein: 10,
    carbs: 56,
    fat: 14,
    tags: ["light"],
    ingredients: [{"name":"capsicum","qty":120,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Roti + Capsicum Masala")
  },
  {
    id: "d24",
    name: "Roti + Gatte Ki Sabzi",
    emoji: "🍛",
    slots: ["dinner"],
    kcal: 510,
    protein: 16,
    carbs: 62,
    fat: 18,
    tags: ["legume"],
    ingredients: [{"name":"gram flour","qty":60,"unit":"g","category":"legume"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"yogurt","qty":50,"unit":"g","category":"dairy"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "gujarati",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 40,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Roti + Gatte Ki Sabzi")
  },
  {
    id: "d25",
    name: "Roti + Methi Matar Malai",
    emoji: "🥬",
    slots: ["dinner"],
    kcal: 510,
    protein: 12,
    carbs: 55,
    fat: 20,
    tags: ["leafy","light"],
    ingredients: [{"name":"fenugreek leaves","qty":80,"unit":"g","category":"veg"},{"name":"peas","qty":80,"unit":"g","category":"veg"},{"name":"cream","qty":20,"unit":"ml","category":"dairy"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Roti + Methi Matar Malai")
  },
  {
    id: "d26",
    name: "Roti + Patta Gobi Sabzi",
    emoji: "🥬",
    slots: ["dinner"],
    kcal: 410,
    protein: 10,
    carbs: 54,
    fat: 12,
    tags: ["leafy","light"],
    ingredients: [{"name":"cabbage","qty":150,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Roti + Patta Gobi Sabzi")
  },
  {
    id: "d27",
    name: "Roti + Sev Tamatar",
    emoji: "🍅",
    slots: ["dinner"],
    kcal: 480,
    protein: 12,
    carbs: 58,
    fat: 18,
    tags: ["light"],
    ingredients: [{"name":"tomato","qty":150,"unit":"g","category":"veg"},{"name":"sev","qty":40,"unit":"g","category":"grain"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "gujarati",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Roti + Sev Tamatar")
  },
  {
    id: "d28",
    name: "Roti + Stuffed Capsicum",
    emoji: "🫑",
    slots: ["dinner"],
    kcal: 450,
    protein: 12,
    carbs: 58,
    fat: 15,
    tags: ["light"],
    ingredients: [{"name":"capsicum","qty":120,"unit":"g","category":"veg"},{"name":"potato","qty":80,"unit":"g","category":"veg"},{"name":"paneer","qty":30,"unit":"g","category":"dairy"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Roti + Stuffed Capsicum")
  },
  {
    id: "d29",
    name: "Sabudana Khichadi",
    emoji: "🥣",
    slots: ["dinner"],
    kcal: 390,
    protein: 5,
    carbs: 62,
    fat: 12,
    tags: ["light"],
    ingredients: [{"name":"sabudana","qty":80,"unit":"g","category":"grain"},{"name":"peanuts","qty":20,"unit":"g","category":"nut"},{"name":"potato","qty":60,"unit":"g","category":"veg"},{"name":"oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "maharashtrian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Sabudana Khichadi")
  },
  {
    id: "d30",
    name: "Schezwan Fried Rice",
    emoji: "🥡",
    slots: ["dinner"],
    kcal: 540,
    protein: 10,
    carbs: 82,
    fat: 16,
    tags: ["light"],
    ingredients: [{"name":"rice","qty":100,"unit":"g","category":"grain"},{"name":"mixed veg","qty":80,"unit":"g","category":"veg"},{"name":"schezwan sauce","qty":20,"unit":"g","category":"spice"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "indo-chinese",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 3,
    recipeUrl: youtubeSearchUrl("Schezwan Fried Rice")
  },
  {
    id: "l28",
    name: "Soya Keema + Roti",
    emoji: "🍛",
    slots: ["lunch"],
    kcal: 510,
    protein: 25,
    carbs: 68,
    fat: 15,
    tags: ["legume"],
    ingredients: [{"name":"soya granules","qty":50,"unit":"g","category":"legume"},{"name":"onion","qty":50,"unit":"g","category":"veg"},{"name":"tomato","qty":50,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Soya Keema + Roti")
  },
  {
    id: "l29",
    name: "Soya Keema Matar + Roti",
    emoji: "🍛",
    slots: ["lunch"],
    kcal: 530,
    protein: 26,
    carbs: 70,
    fat: 16,
    tags: ["legume"],
    ingredients: [{"name":"soya granules","qty":50,"unit":"g","category":"legume"},{"name":"peas","qty":50,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Soya Keema Matar + Roti")
  },
  {
    id: "l30",
    name: "Soya Keema Stuffed Paratha",
    emoji: "🫓",
    slots: ["lunch"],
    kcal: 470,
    protein: 18,
    carbs: 62,
    fat: 16,
    tags: ["paratha","legume"],
    ingredients: [{"name":"wheat flour","qty":75,"unit":"g","category":"grain"},{"name":"soya granules","qty":40,"unit":"g","category":"legume"},{"name":"ghee","qty":12,"unit":"g","category":"dairy"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 35,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Soya Keema Stuffed Paratha")
  },
  {
    id: "d31",
    name: "Tomato Soup + Chopped Green Salad",
    emoji: "🥗",
    slots: ["dinner"],
    kcal: 310,
    protein: 8,
    carbs: 40,
    fat: 10,
    tags: ["light"],
    ingredients: [{"name":"tomato","qty":200,"unit":"g","category":"veg"},{"name":"mixed salad veg","qty":150,"unit":"g","category":"veg"},{"name":"olive oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove","blender"],
    prepMinutes: 20,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Tomato Soup + Chopped Green Salad")
  },
  {
    id: "d32",
    name: "Veg Fried Rice + Chilli Paneer",
    emoji: "🥡",
    slots: ["dinner"],
    kcal: 640,
    protein: 20,
    carbs: 80,
    fat: 24,
    tags: ["light"],
    ingredients: [{"name":"rice","qty":100,"unit":"g","category":"grain"},{"name":"paneer","qty":80,"unit":"g","category":"dairy"},{"name":"mixed veg","qty":80,"unit":"g","category":"veg"},{"name":"oil","qty":15,"unit":"ml","category":"oil"}],
    cuisine: "indo-chinese",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 35,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Veg Fried Rice + Chilli Paneer")
  },
  {
    id: "d33",
    name: "Veg Pizza Night",
    emoji: "🍕",
    slots: ["dinner"],
    kcal: 720,
    protein: 22,
    carbs: 85,
    fat: 28,
    tags: ["pizza"],
    ingredients: [{"name":"pizza base","qty":150,"unit":"g","category":"grain"},{"name":"cheese","qty":60,"unit":"g","category":"dairy"},{"name":"mixed veg","qty":80,"unit":"g","category":"veg"},{"name":"tomato sauce","qty":40,"unit":"g","category":"veg"}],
    cuisine: "continental",
    cookingType: "baked",
    equipment: ["oven"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Veg Pizza Night")
  },
  {
    id: "l31",
    name: "Veg Pulao + Roti",
    emoji: "🍚",
    slots: ["lunch"],
    kcal: 540,
    protein: 12,
    carbs: 80,
    fat: 14,
    tags: ["light"],
    ingredients: [{"name":"basmati rice","qty":80,"unit":"g","category":"grain"},{"name":"mixed veg","qty":100,"unit":"g","category":"veg"},{"name":"wheat flour","qty":30,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Veg Pulao + Roti")
  },
  {
    id: "l32",
    name: "Vegetable Upma",
    emoji: "🥣",
    slots: ["lunch"],
    kcal: 360,
    protein: 9,
    carbs: 60,
    fat: 9,
    tags: ["light"],
    ingredients: [{"name":"semolina","qty":80,"unit":"g","category":"grain"},{"name":"mixed veg","qty":80,"unit":"g","category":"veg"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Vegetable Upma")
  },
  {
    id: "d34",
    name: "Vegetable Uttapam",
    emoji: "🥞",
    slots: ["dinner"],
    kcal: 380,
    protein: 10,
    carbs: 62,
    fat: 8,
    tags: ["light"],
    ingredients: [{"name":"dosa batter","qty":150,"unit":"g","category":"grain"},{"name":"onion","qty":30,"unit":"g","category":"veg"},{"name":"tomato","qty":30,"unit":"g","category":"veg"},{"name":"oil","qty":6,"unit":"ml","category":"oil"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Vegetable Uttapam")
  },
  {
    id: "d35",
    name: "White Sauce Protein Pasta",
    emoji: "🍝",
    slots: ["dinner"],
    kcal: 610,
    protein: 26,
    carbs: 70,
    fat: 18,
    tags: ["legume"],
    ingredients: [{"name":"chickpea pasta","qty":100,"unit":"g","category":"grain"},{"name":"milk","qty":150,"unit":"ml","category":"dairy"},{"name":"cheese","qty":25,"unit":"g","category":"dairy"},{"name":"flour","qty":10,"unit":"g","category":"grain"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("White Sauce Protein Pasta")
  }
];

export const DISHES_BY_ID: Record<string, Dish> = Object.fromEntries(DISHES.map((d) => [d.id, d]));

export function dishesForSlot(slot: Slot): Dish[] {
  return DISHES.filter((d) => d.slots.includes(slot));
}
