export type Slot = "breakfast" | "lunch" | "dinner";
export type IngredientCategory =
  | "veg"
  | "grain"
  | "dairy"
  | "legume"
  | "spice"
  | "oil"
  | "fruit"
  | "nut"
  | "other";

export interface Ingredient {
  name: string;
  qty: number;
  unit: "g" | "ml" | "pc";
  category: IngredientCategory;
}

export type Cuisine =
  | "north-indian"
  | "south-indian"
  | "gujarati"
  | "punjabi"
  | "bengali"
  | "maharashtrian"
  | "indo-chinese"
  | "continental";

export type CookingType =
  | "stovetop"
  | "no-cook"
  | "steamed"
  | "baked"
  | "fried"
  | "grilled"
  | "instant-pot";

export type Equipment =
  | "stove"
  | "oven"
  | "airfryer"
  | "microwave"
  | "blender"
  | "pressure-cooker"
  | "griddle";

export interface Dish {
  id: string;
  name: string;
  emoji: string;
  slots: Slot[];
  kcal: number;
  protein: number; // g
  carbs: number; // g
  fat: number; // g
  tags: DishTag[];
  ingredients: Ingredient[];
  cuisine?: Cuisine;
  cookingType?: CookingType;
  equipment?: Equipment[];
  prepMinutes?: number;
  spiceLevel?: 0 | 1 | 2 | 3;
  recipeUrl?: string;
}

export type DishTag =
  | "pizza"
  | "paratha"
  | "fried-breakfast"
  | "dal"
  | "legume"
  | "leafy"
  | "sweet"
  | "light"
  | "heavy"
  | "medium"
  | "high-protein"
  | "paneer"
  | "soya"
  | "potato"
  | "rice"
  | "flour"
  | "pasta"
  | "veg"
  | "south-indian"
  | "gujarati"
  | "maharashtrian"
  | "indo-chinese"
  | "continental"
  | "street-food"
  | "soup"
  | "salad"
  | "chana-rajma"
  | "kadhi"
  | "khichdi"
  | "poha-upma";

export const CATEGORY_EMOJI: Record<IngredientCategory, string> = {
  veg: "🥬",
  grain: "🌾",
  dairy: "🥛",
  legume: "🫘",
  spice: "🧂",
  oil: "🫒",
  fruit: "🍎",
  nut: "🥜",
  other: "🧺",
};

export const CUISINE_LABELS: Record<Cuisine, string> = {
  "north-indian": "North Indian",
  "south-indian": "South Indian",
  "gujarati": "Gujarati",
  "punjabi": "Punjabi",
  "bengali": "Bengali",
  "maharashtrian": "Maharashtrian",
  "indo-chinese": "Indo-Chinese",
  "continental": "Continental",
};

export function getDishBase(dish: Dish): string {
  const n = dish.name.toLowerCase();
  if (dish.tags.includes("paratha") || n.includes("paratha")) return "Paratha";
  if (dish.tags.includes("pizza") || n.includes("pizza")) return "Pizza";
  if (n.includes("roti") || n.includes("phulka") || n.includes("chapati")) return "Roti";
  if (n.includes("rice") || n.includes("pulao") || n.includes("biryani") || n.includes("khichdi")) return "Rice";
  if (n.includes("dosa") || n.includes("idli") || n.includes("uttapam")) return "Dosa/Idli";
  if (n.includes("poha") || n.includes("upma")) return "Poha/Upma";
  if (n.includes("puri") || n.includes("poori")) return "Puri";
  if (n.includes("paneer")) return "Paneer";
  if (dish.tags.includes("dal") || dish.tags.includes("legume") || n.includes("dal") || n.includes("curry")) return "Dal & Curry";
  if (dish.tags.includes("light")) return "Light Meal";
  return "Special";
}

export function youtubeSearchUrl(name: string): string {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(name + " recipe")}`;
}

export const DISHES: Dish[] = [

  {
    id: "l1",
    name: "Achari Paneer + Roti",
    emoji: "🧀",
    slots: ["lunch"],
    kcal: 610,
    protein: 24,
    carbs: 56,
    fat: 28,
    tags: ["heavy", "paneer", "high-protein", "flour"],
    ingredients: [{"name":"paneer","qty":100,"unit":"g","category":"dairy"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"achari masala","qty":10,"unit":"g","category":"spice"},{"name":"oil","qty":12,"unit":"ml","category":"oil"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Achari Paneer + Roti")
  },
  {
    id: "d1",
    name: "Air Fryer Manchurian + Noodles",
    emoji: "🥡",
    slots: ["dinner"],
    kcal: 590,
    protein: 14,
    carbs: 80,
    fat: 20,
    tags: ["light", "pasta", "indo-chinese"],
    ingredients: [{"name":"noodles","qty":80,"unit":"g","category":"grain"},{"name":"mixed veg","qty":120,"unit":"g","category":"veg"},{"name":"oil","qty":12,"unit":"ml","category":"oil"}],
    cuisine: "indo-chinese",
    cookingType: "baked",
    equipment: ["airfryer","stove"],
    prepMinutes: 40,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Air Fryer Manchurian + Noodles")
  },
  {
    id: "d2",
    name: "Air Fryer Protein Cutlets",
    emoji: "🧆",
    slots: ["dinner"],
    kcal: 380,
    protein: 18,
    carbs: 45,
    fat: 12,
    tags: ["light", "legume", "continental"],
    ingredients: [{"name":"paneer","qty":50,"unit":"g","category":"dairy"},{"name":"soya granules","qty":30,"unit":"g","category":"legume"},{"name":"potato","qty":50,"unit":"g","category":"veg"},{"name":"breadcrumbs","qty":20,"unit":"g","category":"grain"}],
    cuisine: "continental",
    cookingType: "baked",
    equipment: ["airfryer"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Air Fryer Protein Cutlets")
  },
  {
    id: "d3",
    name: "Air Fryer Spring Rolls & Nuggets",
    emoji: "🍟",
    slots: ["dinner"],
    kcal: 440,
    protein: 12,
    carbs: 55,
    fat: 16,
    tags: ["light", "flour", "indo-chinese"],
    ingredients: [{"name":"frozen spring rolls & nuggets","qty":150,"unit":"g","category":"other"},{"name":"oil spray","qty":5,"unit":"ml","category":"oil"}],
    cuisine: "indo-chinese",
    cookingType: "baked",
    equipment: ["airfryer"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Air Fryer Spring Rolls & Nuggets")
  },
  {
    id: "l2",
    name: "Aloo Gobi + Roti",
    emoji: "🥔",
    slots: ["lunch"],
    kcal: 520,
    protein: 14,
    carbs: 70,
    fat: 18,
    tags: ["light", "veg", "potato", "flour"],
    ingredients: [{"name":"potato","qty":120,"unit":"g","category":"veg"},{"name":"cauliflower","qty":120,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":12,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Aloo Gobi + Roti")
  },
  {
    id: "l3",
    name: "Aloo Paratha",
    emoji: "🫓",
    slots: ["lunch"],
    kcal: 480,
    protein: 11,
    carbs: 60,
    fat: 20,
    tags: ["paratha", "heavy", "potato", "flour"],
    ingredients: [{"name":"wheat flour","qty":80,"unit":"g","category":"grain"},{"name":"potato","qty":120,"unit":"g","category":"veg"},{"name":"ghee","qty":15,"unit":"g","category":"dairy"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Aloo Paratha")
  },
  {
    id: "l4",
    name: "Aloo Sabzi + Roti",
    emoji: "🥔",
    slots: ["lunch"],
    kcal: 480,
    protein: 10,
    carbs: 65,
    fat: 16,
    tags: ["light", "potato", "flour"],
    ingredients: [{"name":"potato","qty":150,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Aloo Sabzi + Roti")
  },
  {
    id: "d4",
    name: "Arrabbiata Pasta",
    emoji: "🍝",
    slots: ["dinner"],
    kcal: 510,
    protein: 14,
    carbs: 78,
    fat: 12,
    tags: ["light", "pasta", "continental"],
    ingredients: [{"name":"pasta","qty":100,"unit":"g","category":"grain"},{"name":"tomato pureee","qty":100,"unit":"g","category":"veg"},{"name":"chilli flakes & herbs","qty":5,"unit":"g","category":"spice"},{"name":"olive oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Arrabbiata Pasta")
  },
  {
    id: "b1",
    name: "Banana + Whey Shake",
    emoji: "🥤",
    slots: ["breakfast"],
    kcal: 320,
    protein: 28,
    carbs: 40,
    fat: 5,
    tags: ["light", "high-protein", "continental"],
    ingredients: [{"name":"whey protein","qty":30,"unit":"g","category":"other"},{"name":"banana","qty":1,"unit":"pc","category":"fruit"},{"name":"peanut butter","qty":15,"unit":"g","category":"nut"},{"name":"milk","qty":200,"unit":"ml","category":"dairy"}],
    cuisine: "continental",
    cookingType: "no-cook",
    equipment: ["blender"],
    prepMinutes: 5,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Banana + Whey Shake")
  },
  {
    id: "d5",
    name: "Besan Chilla",
    emoji: "🥞",
    slots: ["dinner"],
    kcal: 320,
    protein: 15,
    carbs: 32,
    fat: 12,
    tags: ["light", "legume"],
    ingredients: [{"name":"gram flour","qty":70,"unit":"g","category":"legume"},{"name":"onion","qty":40,"unit":"g","category":"veg"},{"name":"tomato","qty":40,"unit":"g","category":"veg"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Besan Chilla")
  },
  {
    id: "l5",
    name: "Black Chana + Roti",
    emoji: "🫘",
    slots: ["lunch"],
    kcal: 530,
    protein: 19,
    carbs: 72,
    fat: 12,
    tags: ["chana-rajma", "legume", "flour", "medium"],
    ingredients: [{"name":"black chickpeas","qty":80,"unit":"g","category":"legume"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"onion","qty":40,"unit":"g","category":"veg"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove","pressure-cooker"],
    prepMinutes: 40,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Black Chana + Roti")
  },
  {
    id: "d6",
    name: "Broccoli Almond Soup + Caesar-style Salad",
    emoji: "🥗",
    slots: ["dinner"],
    kcal: 340,
    protein: 10,
    carbs: 32,
    fat: 16,
    tags: ["soup", "veg", "continental", "light", "salad"],
    ingredients: [{"name":"broccoli","qty":150,"unit":"g","category":"veg"},{"name":"almonds","qty":20,"unit":"g","category":"nut"},{"name":"salad leaves","qty":100,"unit":"g","category":"veg"},{"name":"olive oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove","blender"],
    prepMinutes: 25,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Broccoli Almond Soup + Caesar-style Salad")
  },
  {
    id: "l6",
    name: "Chole + Rice",
    emoji: "🍛",
    slots: ["lunch"],
    kcal: 610,
    protein: 21,
    carbs: 92,
    fat: 14,
    tags: ["heavy", "legume", "rice", "high-protein", "chana-rajma"],
    ingredients: [{"name":"chickpeas","qty":90,"unit":"g","category":"legume"},{"name":"rice","qty":100,"unit":"g","category":"grain"},{"name":"onion","qty":60,"unit":"g","category":"veg"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "punjabi",
    cookingType: "instant-pot",
    equipment: ["pressure-cooker"],
    prepMinutes: 40,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Chole + Rice")
  },
  {
    id: "l7",
    name: "Chole Bhature/Kulche",
    emoji: "🫓",
    slots: ["lunch"],
    kcal: 650,
    protein: 18,
    carbs: 82,
    fat: 28,
    tags: ["fried-breakfast", "heavy", "legume", "chana-rajma"],
    ingredients: [{"name":"chickpeas","qty":80,"unit":"g","category":"legume"},{"name":"maida","qty":90,"unit":"g","category":"grain"},{"name":"oil","qty":30,"unit":"ml","category":"oil"},{"name":"onion","qty":40,"unit":"g","category":"veg"}],
    cuisine: "punjabi",
    cookingType: "fried",
    equipment: ["stove"],
    prepMinutes: 60,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Chole Bhature/Kulche")
  },
  {
    id: "b2",
    name: "Curd + Fruits",
    emoji: "🍏",
    slots: ["breakfast"],
    kcal: 210,
    protein: 8,
    carbs: 32,
    fat: 5,
    tags: ["light"],
    ingredients: [{"name":"curd","qty":150,"unit":"g","category":"dairy"},{"name":"apple","qty":1,"unit":"pc","category":"fruit"},{"name":"pomegranate seeds","qty":50,"unit":"g","category":"fruit"},{"name":"honey","qty":10,"unit":"g","category":"other"}],
    cuisine: "north-indian",
    cookingType: "no-cook",
    equipment: [],
    prepMinutes: 5,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Curd + Fruits")
  },
  {
    id: "l8",
    name: "Dal Baati",
    emoji: "🫓",
    slots: ["lunch"],
    kcal: 680,
    protein: 20,
    carbs: 85,
    fat: 26,
    tags: ["heavy", "legume", "gujarati", "high-protein", "dal", "flour"],
    ingredients: [{"name":"wheat flour","qty":100,"unit":"g","category":"grain"},{"name":"mixed dal","qty":60,"unit":"g","category":"legume"},{"name":"ghee","qty":25,"unit":"g","category":"dairy"}],
    cuisine: "gujarati",
    cookingType: "baked",
    equipment: ["oven","stove"],
    prepMinutes: 60,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Dal Baati")
  },
  {
    id: "d7",
    name: "Dal Dhokli",
    emoji: "🍲",
    slots: ["dinner"],
    kcal: 480,
    protein: 18,
    carbs: 70,
    fat: 12,
    tags: ["light", "dal", "legume", "gujarati"],
    ingredients: [{"name":"toor dal","qty":60,"unit":"g","category":"legume"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"ghee","qty":10,"unit":"g","category":"dairy"}],
    cuisine: "gujarati",
    cookingType: "stovetop",
    equipment: ["pressure-cooker"],
    prepMinutes: 45,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Dal Dhokli")
  },
  {
    id: "l9",
    name: "Dal Palak + Rice",
    emoji: "🍛",
    slots: ["lunch"],
    kcal: 520,
    protein: 19,
    carbs: 80,
    fat: 10,
    tags: ["legume", "rice", "leafy", "dal", "medium"],
    ingredients: [{"name":"toor dal","qty":70,"unit":"g","category":"legume"},{"name":"spinach","qty":100,"unit":"g","category":"veg"},{"name":"rice","qty":100,"unit":"g","category":"grain"},{"name":"oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove","pressure-cooker"],
    prepMinutes: 35,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Dal Palak + Rice")
  },
  {
    id: "b3",
    name: "Fruit + Whey",
    emoji: "🍌",
    slots: ["breakfast"],
    kcal: 260,
    protein: 26,
    carbs: 30,
    fat: 3,
    tags: ["light", "high-protein", "continental"],
    ingredients: [{"name":"whey protein","qty":30,"unit":"g","category":"other"},{"name":"banana","qty":1,"unit":"pc","category":"fruit"},{"name":"milk","qty":150,"unit":"ml","category":"dairy"}],
    cuisine: "continental",
    cookingType: "no-cook",
    equipment: ["blender"],
    prepMinutes: 5,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Fruit + Whey")
  },
  {
    id: "b4",
    name: "Fruit Bowl",
    emoji: "🥣",
    slots: ["breakfast"],
    kcal: 180,
    protein: 3,
    carbs: 42,
    fat: 1,
    tags: ["light", "continental"],
    ingredients: [{"name":"papaya","qty":100,"unit":"g","category":"fruit"},{"name":"apple","qty":1,"unit":"pc","category":"fruit"},{"name":"banana","qty":1,"unit":"pc","category":"fruit"},{"name":"pomegranate seeds","qty":50,"unit":"g","category":"fruit"}],
    cuisine: "continental",
    cookingType: "no-cook",
    equipment: [],
    prepMinutes: 5,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Fruit Bowl")
  },
  {
    id: "d8",
    name: "Garlic Bread + Light Soup Blend",
    emoji: "🍞",
    slots: ["dinner"],
    kcal: 390,
    protein: 11,
    carbs: 54,
    fat: 13,
    tags: ["light", "continental", "flour", "soup"],
    ingredients: [{"name":"bread","qty":80,"unit":"g","category":"grain"},{"name":"mixed soup veg","qty":150,"unit":"g","category":"veg"},{"name":"butter & garlic","qty":15,"unit":"g","category":"dairy"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Garlic Bread + Light Soup Blend")
  },
  {
    id: "l10",
    name: "Gobi Matar + Roti",
    emoji: "🥦",
    slots: ["lunch"],
    kcal: 480,
    protein: 12,
    carbs: 64,
    fat: 15,
    tags: ["light", "veg", "flour"],
    ingredients: [{"name":"cauliflower","qty":120,"unit":"g","category":"veg"},{"name":"peas","qty":80,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Gobi Matar + Roti")
  },
  {
    id: "l11",
    name: "Gobi Paratha",
    emoji: "🫓",
    slots: ["lunch"],
    kcal: 460,
    protein: 12,
    carbs: 58,
    fat: 19,
    tags: ["paratha", "veg", "heavy", "flour"],
    ingredients: [{"name":"wheat flour","qty":80,"unit":"g","category":"grain"},{"name":"cauliflower","qty":120,"unit":"g","category":"veg"},{"name":"ghee","qty":15,"unit":"g","category":"dairy"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Gobi Paratha")
  },
  {
    id: "b5",
    name: "Greek Yogurt + Fruits",
    emoji: "🍓",
    slots: ["breakfast"],
    kcal: 220,
    protein: 15,
    carbs: 28,
    fat: 4,
    tags: ["light", "continental"],
    ingredients: [{"name":"greek yogurt","qty":150,"unit":"g","category":"dairy"},{"name":"mixed berries","qty":80,"unit":"g","category":"fruit"},{"name":"honey","qty":10,"unit":"g","category":"other"}],
    cuisine: "continental",
    cookingType: "no-cook",
    equipment: [],
    prepMinutes: 5,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Greek Yogurt + Fruits")
  },
  {
    id: "d9",
    name: "Handvo",
    emoji: "🥮",
    slots: ["dinner"],
    kcal: 410,
    protein: 14,
    carbs: 62,
    fat: 10,
    tags: ["light", "legume", "gujarati"],
    ingredients: [{"name":"rice & lentil batter","qty":150,"unit":"g","category":"grain"},{"name":"bottle gourd","qty":50,"unit":"g","category":"veg"},{"name":"oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "gujarati",
    cookingType: "baked",
    equipment: ["oven","stove"],
    prepMinutes: 45,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Handvo")
  },
  {
    id: "d10",
    name: "High Protein Red Sauce Pasta",
    emoji: "🍝",
    slots: ["dinner"],
    kcal: 580,
    protein: 28,
    carbs: 75,
    fat: 14,
    tags: ["legume", "continental", "high-protein", "pasta", "medium"],
    ingredients: [{"name":"chickpea pasta","qty":100,"unit":"g","category":"grain"},{"name":"tomato sauce","qty":100,"unit":"g","category":"veg"},{"name":"cheese","qty":20,"unit":"g","category":"dairy"},{"name":"oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("High Protein Red Sauce Pasta")
  },
  {
    id: "l12",
    name: "Kadai Paneer + Roti",
    emoji: "🌶️",
    slots: ["lunch"],
    kcal: 640,
    protein: 26,
    carbs: 58,
    fat: 32,
    tags: ["heavy", "paneer", "high-protein", "flour"],
    ingredients: [{"name":"paneer","qty":120,"unit":"g","category":"dairy"},{"name":"capsicum","qty":80,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"onion","qty":50,"unit":"g","category":"veg"},{"name":"oil","qty":15,"unit":"ml","category":"oil"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Kadai Paneer + Roti")
  },
  {
    id: "d11",
    name: "Light Dahi Sandwich",
    emoji: "🥪",
    slots: ["dinner"],
    kcal: 340,
    protein: 12,
    carbs: 45,
    fat: 11,
    tags: ["light", "continental"],
    ingredients: [{"name":"bread","qty":80,"unit":"g","category":"grain"},{"name":"hung curd","qty":60,"unit":"g","category":"dairy"},{"name":"cucumber","qty":30,"unit":"g","category":"veg"},{"name":"butter","qty":5,"unit":"g","category":"dairy"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 15,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Light Dahi Sandwich")
  },
  {
    id: "l13",
    name: "Methi Aloo + Roti",
    emoji: "🥔",
    slots: ["lunch"],
    kcal: 480,
    protein: 12,
    carbs: 64,
    fat: 15,
    tags: ["leafy", "potato", "flour", "medium"],
    ingredients: [{"name":"fenugreek leaves","qty":100,"unit":"g","category":"veg"},{"name":"potato","qty":100,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Methi Aloo + Roti")
  },
  {
    id: "l14",
    name: "Methi Malai Paneer + Roti",
    emoji: "🥬",
    slots: ["lunch"],
    kcal: 630,
    protein: 25,
    carbs: 54,
    fat: 32,
    tags: ["heavy", "high-protein", "paneer", "leafy", "flour"],
    ingredients: [{"name":"paneer","qty":100,"unit":"g","category":"dairy"},{"name":"fenugreek leaves","qty":80,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"cream","qty":20,"unit":"ml","category":"dairy"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Methi Malai Paneer + Roti")
  },
  {
    id: "l15",
    name: "Mix Veg Curry + Roti",
    emoji: "🥕",
    slots: ["lunch"],
    kcal: 520,
    protein: 14,
    carbs: 66,
    fat: 20,
    tags: ["light", "veg", "flour"],
    ingredients: [{"name":"mixed veg","qty":200,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":12,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Mix Veg Curry + Roti")
  },
  {
    id: "d12",
    name: "Moong Dal Chilla",
    emoji: "🥞",
    slots: ["dinner"],
    kcal: 340,
    protein: 16,
    carbs: 45,
    fat: 8,
    tags: ["light", "legume", "south-indian"],
    ingredients: [{"name":"moong dal","qty":80,"unit":"g","category":"legume"},{"name":"ginger","qty":5,"unit":"g","category":"spice"},{"name":"oil","qty":6,"unit":"ml","category":"oil"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Moong Dal Chilla")
  },
  {
    id: "d13",
    name: "Moong Dal Khichdi",
    emoji: "🍲",
    slots: ["dinner"],
    kcal: 440,
    protein: 16,
    carbs: 68,
    fat: 8,
    tags: ["legume", "rice", "light", "khichdi", "dal"],
    ingredients: [{"name":"rice","qty":60,"unit":"g","category":"grain"},{"name":"moong dal","qty":60,"unit":"g","category":"legume"},{"name":"ghee","qty":8,"unit":"g","category":"dairy"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["pressure-cooker"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Moong Dal Khichdi")
  },
  {
    id: "d14",
    name: "Moong Dal Khichdi + Kadhi",
    emoji: "🍛",
    slots: ["dinner"],
    kcal: 490,
    protein: 16,
    carbs: 72,
    fat: 12,
    tags: ["legume", "kadhi", "rice", "light", "khichdi", "dal"],
    ingredients: [{"name":"rice","qty":50,"unit":"g","category":"grain"},{"name":"moong dal","qty":50,"unit":"g","category":"legume"},{"name":"yogurt","qty":80,"unit":"g","category":"dairy"},{"name":"ghee","qty":8,"unit":"g","category":"dairy"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["pressure-cooker"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Moong Dal Khichdi + Kadhi")
  },
  {
    id: "l16",
    name: "Mushroom Masala + Roti",
    emoji: "🍄",
    slots: ["lunch"],
    kcal: 490,
    protein: 15,
    carbs: 60,
    fat: 16,
    tags: ["light", "veg", "flour"],
    ingredients: [{"name":"mushrooms","qty":150,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"onion","qty":50,"unit":"g","category":"veg"},{"name":"tomato","qty":50,"unit":"g","category":"veg"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Mushroom Masala + Roti")
  },
  {
    id: "d15",
    name: "Mushroom Pizza",
    emoji: "🍕",
    slots: ["dinner"],
    kcal: 710,
    protein: 20,
    carbs: 82,
    fat: 26,
    tags: ["heavy", "veg", "pizza", "continental", "high-protein"],
    ingredients: [{"name":"pizza base","qty":150,"unit":"g","category":"grain"},{"name":"mushrooms","qty":100,"unit":"g","category":"veg"},{"name":"cheese","qty":60,"unit":"g","category":"dairy"},{"name":"tomato sauce","qty":40,"unit":"g","category":"veg"}],
    cuisine: "continental",
    cookingType: "baked",
    equipment: ["oven"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Mushroom Pizza")
  },
  {
    id: "l17",
    name: "Mushroom Pulao",
    emoji: "🍄",
    slots: ["lunch"],
    kcal: 500,
    protein: 11,
    carbs: 85,
    fat: 10,
    tags: ["light", "veg", "rice"],
    ingredients: [{"name":"mushrooms","qty":150,"unit":"g","category":"veg"},{"name":"basmati rice","qty":100,"unit":"g","category":"grain"},{"name":"oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Mushroom Pulao")
  },
  {
    id: "d16",
    name: "Mushroom Sandwich",
    emoji: "🥪",
    slots: ["dinner"],
    kcal: 400,
    protein: 12,
    carbs: 50,
    fat: 14,
    tags: ["light", "veg", "continental"],
    ingredients: [{"name":"bread","qty":80,"unit":"g","category":"grain"},{"name":"mushrooms","qty":100,"unit":"g","category":"veg"},{"name":"cheese","qty":20,"unit":"g","category":"dairy"},{"name":"butter","qty":5,"unit":"g","category":"dairy"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Mushroom Sandwich")
  },
  {
    id: "d17",
    name: "Mushroom Soup + Garden Salad",
    emoji: "🥗",
    slots: ["dinner"],
    kcal: 320,
    protein: 9,
    carbs: 38,
    fat: 12,
    tags: ["soup", "veg", "continental", "light", "salad"],
    ingredients: [{"name":"mushrooms","qty":150,"unit":"g","category":"veg"},{"name":"salad leaves","qty":100,"unit":"g","category":"veg"},{"name":"cream","qty":15,"unit":"ml","category":"dairy"},{"name":"olive oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove","blender"],
    prepMinutes: 25,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Mushroom Soup + Garden Salad")
  },
  {
    id: "b6",
    name: "Overnight Oats",
    emoji: "🥣",
    slots: ["breakfast"],
    kcal: 350,
    protein: 12,
    carbs: 55,
    fat: 8,
    tags: ["light", "continental"],
    ingredients: [{"name":"oats","qty":50,"unit":"g","category":"grain"},{"name":"milk","qty":150,"unit":"ml","category":"dairy"},{"name":"chia seeds","qty":10,"unit":"g","category":"nut"},{"name":"honey","qty":10,"unit":"g","category":"other"},{"name":"banana","qty":1,"unit":"pc","category":"fruit"}],
    cuisine: "continental",
    cookingType: "no-cook",
    equipment: [],
    prepMinutes: 5,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Overnight Oats")
  },
  {
    id: "l18",
    name: "Palak Paneer + Roti",
    emoji: "🥬",
    slots: ["lunch"],
    kcal: 620,
    protein: 28,
    carbs: 55,
    fat: 28,
    tags: ["heavy", "high-protein", "paneer", "leafy", "flour"],
    ingredients: [{"name":"paneer","qty":120,"unit":"g","category":"dairy"},{"name":"spinach","qty":150,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":12,"unit":"ml","category":"oil"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["stove","blender"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Palak Paneer + Roti")
  },
  {
    id: "l19",
    name: "Paneer Bhurji + Roti",
    emoji: "🧀",
    slots: ["lunch"],
    kcal: 560,
    protein: 26,
    carbs: 50,
    fat: 28,
    tags: ["light", "high-protein", "paneer", "flour"],
    ingredients: [{"name":"paneer","qty":120,"unit":"g","category":"dairy"},{"name":"onion","qty":50,"unit":"g","category":"veg"},{"name":"tomato","qty":50,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"ghee","qty":10,"unit":"g","category":"dairy"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Paneer Bhurji + Roti")
  },
  {
    id: "l20",
    name: "Paneer Paratha",
    emoji: "🫓",
    slots: ["dinner","lunch"],
    kcal: 520,
    protein: 18,
    carbs: 58,
    fat: 22,
    tags: ["paratha", "heavy", "paneer", "flour"],
    ingredients: [{"name":"wheat flour","qty":70,"unit":"g","category":"grain"},{"name":"paneer","qty":60,"unit":"g","category":"dairy"},{"name":"ghee","qty":12,"unit":"g","category":"dairy"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Paneer Paratha")
  },
  {
    id: "l21",
    name: "Paneer Pulao",
    emoji: "🍚",
    slots: ["lunch"],
    kcal: 580,
    protein: 20,
    carbs: 80,
    fat: 18,
    tags: ["light", "high-protein", "paneer", "rice"],
    ingredients: [{"name":"paneer","qty":80,"unit":"g","category":"dairy"},{"name":"basmati rice","qty":100,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Paneer Pulao")
  },
  {
    id: "l22",
    name: "Paneer Tikka + Roti",
    emoji: "🧀",
    slots: ["lunch"],
    kcal: 610,
    protein: 26,
    carbs: 50,
    fat: 28,
    tags: ["heavy", "paneer", "high-protein", "flour"],
    ingredients: [{"name":"paneer","qty":120,"unit":"g","category":"dairy"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"yogurt","qty":40,"unit":"g","category":"dairy"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "punjabi",
    cookingType: "grilled",
    equipment: ["griddle"],
    prepMinutes: 35,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Paneer Tikka + Roti")
  },
  {
    id: "l23",
    name: "Paneer Tikka Masala + Roti",
    emoji: "🧀",
    slots: ["lunch"],
    kcal: 630,
    protein: 26,
    carbs: 54,
    fat: 30,
    tags: ["heavy", "paneer", "high-protein", "flour"],
    ingredients: [{"name":"paneer","qty":100,"unit":"g","category":"dairy"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"yogurt","qty":50,"unit":"g","category":"dairy"},{"name":"oil","qty":12,"unit":"ml","category":"oil"}],
    cuisine: "punjabi",
    cookingType: "grilled",
    equipment: ["stove","griddle"],
    prepMinutes: 40,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Paneer Tikka Masala + Roti")
  },
  {
    id: "d18",
    name: "Paneer Tikka Pizza",
    emoji: "🍕",
    slots: ["dinner"],
    kcal: 740,
    protein: 26,
    carbs: 82,
    fat: 30,
    tags: ["heavy", "pizza", "paneer", "continental", "high-protein"],
    ingredients: [{"name":"pizza base","qty":150,"unit":"g","category":"grain"},{"name":"paneer","qty":60,"unit":"g","category":"dairy"},{"name":"cheese","qty":60,"unit":"g","category":"dairy"},{"name":"tomato sauce","qty":40,"unit":"g","category":"veg"}],
    cuisine: "continental",
    cookingType: "baked",
    equipment: ["oven"],
    prepMinutes: 35,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Paneer Tikka Pizza")
  },
  {
    id: "l24",
    name: "Pav Bhaji",
    emoji: "🍞",
    slots: ["lunch"],
    kcal: 600,
    protein: 14,
    carbs: 80,
    fat: 22,
    tags: ["heavy", "maharashtrian"],
    ingredients: [{"name":"pav bread","qty":100,"unit":"g","category":"grain"},{"name":"mixed veg","qty":200,"unit":"g","category":"veg"},{"name":"butter","qty":20,"unit":"g","category":"dairy"}],
    cuisine: "maharashtrian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 40,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Pav Bhaji")
  },
  {
    id: "l25",
    name: "Podi Idli",
    emoji: "⚪",
    slots: ["lunch"],
    kcal: 400,
    protein: 11,
    carbs: 68,
    fat: 8,
    tags: ["light", "legume", "south-indian"],
    ingredients: [{"name":"idli batter","qty":150,"unit":"g","category":"grain"},{"name":"podi powder","qty":15,"unit":"g","category":"spice"},{"name":"ghee","qty":8,"unit":"g","category":"dairy"}],
    cuisine: "south-indian",
    cookingType: "steamed",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Podi Idli")
  },
  {
    id: "l26",
    name: "Pyaz Paratha",
    emoji: "🫓",
    slots: ["lunch"],
    kcal: 460,
    protein: 10,
    carbs: 58,
    fat: 18,
    tags: ["paratha", "heavy", "flour"],
    ingredients: [{"name":"wheat flour","qty":80,"unit":"g","category":"grain"},{"name":"onion","qty":100,"unit":"g","category":"veg"},{"name":"ghee","qty":12,"unit":"g","category":"dairy"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Pyaz Paratha")
  },
  {
    id: "l27",
    name: "Rajma + Rice",
    emoji: "🍛",
    slots: ["lunch"],
    kcal: 620,
    protein: 22,
    carbs: 95,
    fat: 14,
    tags: ["heavy", "legume", "rice", "high-protein", "chana-rajma"],
    ingredients: [{"name":"kidney beans","qty":90,"unit":"g","category":"legume"},{"name":"rice","qty":100,"unit":"g","category":"grain"},{"name":"onion","qty":60,"unit":"g","category":"veg"},{"name":"tomato","qty":60,"unit":"g","category":"veg"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "punjabi",
    cookingType: "instant-pot",
    equipment: ["pressure-cooker"],
    prepMinutes: 45,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Rajma + Rice")
  },
  {
    id: "d19",
    name: "Roti + Aloo Matar",
    emoji: "🍲",
    slots: ["dinner"],
    kcal: 460,
    protein: 11,
    carbs: 62,
    fat: 13,
    tags: ["light", "veg", "potato", "flour"],
    ingredients: [{"name":"potato","qty":100,"unit":"g","category":"veg"},{"name":"peas","qty":80,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Roti + Aloo Matar")
  },
  {
    id: "d20",
    name: "Roti + Baingan Bharta",
    emoji: "🍆",
    slots: ["dinner"],
    kcal: 450,
    protein: 11,
    carbs: 56,
    fat: 16,
    tags: ["light", "veg", "flour"],
    ingredients: [{"name":"eggplant","qty":200,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Roti + Baingan Bharta")
  },
  {
    id: "d21",
    name: "Roti + Bharwa Bhindi",
    emoji: "🌿",
    slots: ["dinner"],
    kcal: 430,
    protein: 10,
    carbs: 54,
    fat: 14,
    tags: ["light", "veg", "flour"],
    ingredients: [{"name":"okra","qty":120,"unit":"g","category":"veg"},{"name":"spices","qty":15,"unit":"g","category":"spice"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Roti + Bharwa Bhindi")
  },
  {
    id: "d22",
    name: "Roti + Bhindi Masala",
    emoji: "🌿",
    slots: ["dinner"],
    kcal: 440,
    protein: 11,
    carbs: 58,
    fat: 14,
    tags: ["light", "veg", "flour"],
    ingredients: [{"name":"okra","qty":120,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Roti + Bhindi Masala")
  },
  {
    id: "d23",
    name: "Roti + Capsicum Masala",
    emoji: "🫑",
    slots: ["dinner"],
    kcal: 430,
    protein: 10,
    carbs: 56,
    fat: 14,
    tags: ["light", "veg", "flour"],
    ingredients: [{"name":"capsicum","qty":120,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Roti + Capsicum Masala")
  },
  {
    id: "d24",
    name: "Roti + Gatte Ki Sabzi",
    emoji: "🍛",
    slots: ["dinner"],
    kcal: 510,
    protein: 16,
    carbs: 62,
    fat: 18,
    tags: ["legume", "gujarati", "flour", "medium"],
    ingredients: [{"name":"gram flour","qty":60,"unit":"g","category":"legume"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"yogurt","qty":50,"unit":"g","category":"dairy"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "gujarati",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 40,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Roti + Gatte Ki Sabzi")
  },
  {
    id: "d25",
    name: "Roti + Methi Matar Malai",
    emoji: "🥬",
    slots: ["dinner"],
    kcal: 510,
    protein: 12,
    carbs: 55,
    fat: 20,
    tags: ["light", "leafy", "veg", "flour"],
    ingredients: [{"name":"fenugreek leaves","qty":80,"unit":"g","category":"veg"},{"name":"peas","qty":80,"unit":"g","category":"veg"},{"name":"cream","qty":20,"unit":"ml","category":"dairy"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Roti + Methi Matar Malai")
  },
  {
    id: "d26",
    name: "Roti + Patta Gobi Sabzi",
    emoji: "🥬",
    slots: ["dinner"],
    kcal: 410,
    protein: 10,
    carbs: 54,
    fat: 12,
    tags: ["light", "leafy", "veg", "flour"],
    ingredients: [{"name":"cabbage","qty":150,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Roti + Patta Gobi Sabzi")
  },
  {
    id: "d27",
    name: "Roti + Sev Tamatar",
    emoji: "🍅",
    slots: ["dinner"],
    kcal: 480,
    protein: 12,
    carbs: 58,
    fat: 18,
    tags: ["light", "veg", "gujarati", "flour"],
    ingredients: [{"name":"tomato","qty":150,"unit":"g","category":"veg"},{"name":"sev","qty":40,"unit":"g","category":"grain"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "gujarati",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Roti + Sev Tamatar")
  },
  {
    id: "d28",
    name: "Roti + Stuffed Capsicum",
    emoji: "🫑",
    slots: ["dinner"],
    kcal: 450,
    protein: 12,
    carbs: 58,
    fat: 15,
    tags: ["light", "veg", "flour"],
    ingredients: [{"name":"capsicum","qty":120,"unit":"g","category":"veg"},{"name":"potato","qty":80,"unit":"g","category":"veg"},{"name":"paneer","qty":30,"unit":"g","category":"dairy"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Roti + Stuffed Capsicum")
  },
  {
    id: "d29",
    name: "Sabudana Khichadi",
    emoji: "🥣",
    slots: ["dinner"],
    kcal: 390,
    protein: 5,
    carbs: 62,
    fat: 12,
    tags: ["light", "khichdi", "maharashtrian"],
    ingredients: [{"name":"sabudana","qty":80,"unit":"g","category":"grain"},{"name":"peanuts","qty":20,"unit":"g","category":"nut"},{"name":"potato","qty":60,"unit":"g","category":"veg"},{"name":"oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "maharashtrian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Sabudana Khichadi")
  },
  {
    id: "d30",
    name: "Schezwan Fried Rice",
    emoji: "🥡",
    slots: ["dinner"],
    kcal: 540,
    protein: 10,
    carbs: 82,
    fat: 16,
    tags: ["light", "indo-chinese", "rice"],
    ingredients: [{"name":"rice","qty":100,"unit":"g","category":"grain"},{"name":"mixed veg","qty":80,"unit":"g","category":"veg"},{"name":"schezwan sauce","qty":20,"unit":"g","category":"spice"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "indo-chinese",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 3,
    recipeUrl: youtubeSearchUrl("Schezwan Fried Rice")
  },
  {
    id: "l28",
    name: "Soya Keema + Roti",
    emoji: "🍛",
    slots: ["lunch"],
    kcal: 510,
    protein: 25,
    carbs: 68,
    fat: 15,
    tags: ["legume", "soya", "high-protein", "flour", "medium"],
    ingredients: [{"name":"soya granules","qty":50,"unit":"g","category":"legume"},{"name":"onion","qty":50,"unit":"g","category":"veg"},{"name":"tomato","qty":50,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Soya Keema + Roti")
  },
  {
    id: "l29",
    name: "Soya Keema Matar + Roti",
    emoji: "🍛",
    slots: ["lunch"],
    kcal: 530,
    protein: 26,
    carbs: 70,
    fat: 16,
    tags: ["legume", "veg", "soya", "high-protein", "flour", "medium"],
    ingredients: [{"name":"soya granules","qty":50,"unit":"g","category":"legume"},{"name":"peas","qty":50,"unit":"g","category":"veg"},{"name":"wheat flour","qty":60,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Soya Keema Matar + Roti")
  },
  {
    id: "l30",
    name: "Soya Keema Stuffed Paratha",
    emoji: "🫓",
    slots: ["lunch"],
    kcal: 470,
    protein: 18,
    carbs: 62,
    fat: 16,
    tags: ["heavy", "legume", "soya", "paratha", "flour"],
    ingredients: [{"name":"wheat flour","qty":75,"unit":"g","category":"grain"},{"name":"soya granules","qty":40,"unit":"g","category":"legume"},{"name":"ghee","qty":12,"unit":"g","category":"dairy"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 35,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Soya Keema Stuffed Paratha")
  },
  {
    id: "d31",
    name: "Tomato Soup + Chopped Green Salad",
    emoji: "🥗",
    slots: ["dinner"],
    kcal: 310,
    protein: 8,
    carbs: 40,
    fat: 10,
    tags: ["light", "salad", "continental", "soup"],
    ingredients: [{"name":"tomato","qty":200,"unit":"g","category":"veg"},{"name":"mixed salad veg","qty":150,"unit":"g","category":"veg"},{"name":"olive oil","qty":8,"unit":"ml","category":"oil"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove","blender"],
    prepMinutes: 20,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Tomato Soup + Chopped Green Salad")
  },
  {
    id: "d32",
    name: "Veg Fried Rice + Chilli Paneer",
    emoji: "🥡",
    slots: ["dinner"],
    kcal: 640,
    protein: 20,
    carbs: 80,
    fat: 24,
    tags: ["heavy", "rice", "indo-chinese", "veg", "paneer", "high-protein"],
    ingredients: [{"name":"rice","qty":100,"unit":"g","category":"grain"},{"name":"paneer","qty":80,"unit":"g","category":"dairy"},{"name":"mixed veg","qty":80,"unit":"g","category":"veg"},{"name":"oil","qty":15,"unit":"ml","category":"oil"}],
    cuisine: "indo-chinese",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 35,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Veg Fried Rice + Chilli Paneer")
  },
  {
    id: "d33",
    name: "Veg Pizza Night",
    emoji: "🍕",
    slots: ["dinner"],
    kcal: 720,
    protein: 22,
    carbs: 85,
    fat: 28,
    tags: ["heavy", "veg", "pizza", "continental", "high-protein"],
    ingredients: [{"name":"pizza base","qty":150,"unit":"g","category":"grain"},{"name":"cheese","qty":60,"unit":"g","category":"dairy"},{"name":"mixed veg","qty":80,"unit":"g","category":"veg"},{"name":"tomato sauce","qty":40,"unit":"g","category":"veg"}],
    cuisine: "continental",
    cookingType: "baked",
    equipment: ["oven"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Veg Pizza Night")
  },
  {
    id: "l31",
    name: "Veg Pulao + Roti",
    emoji: "🍚",
    slots: ["lunch"],
    kcal: 540,
    protein: 12,
    carbs: 80,
    fat: 14,
    tags: ["light", "veg", "flour", "rice"],
    ingredients: [{"name":"basmati rice","qty":80,"unit":"g","category":"grain"},{"name":"mixed veg","qty":100,"unit":"g","category":"veg"},{"name":"wheat flour","qty":30,"unit":"g","category":"grain"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Veg Pulao + Roti")
  },
  {
    id: "l32",
    name: "Vegetable Upma",
    emoji: "🥣",
    slots: ["lunch"],
    kcal: 360,
    protein: 9,
    carbs: 60,
    fat: 9,
    tags: ["light", "poha-upma", "veg", "south-indian"],
    ingredients: [{"name":"semolina","qty":80,"unit":"g","category":"grain"},{"name":"mixed veg","qty":80,"unit":"g","category":"veg"},{"name":"oil","qty":10,"unit":"ml","category":"oil"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Vegetable Upma")
  },
  {
    id: "d34",
    name: "Vegetable Uttapam",
    emoji: "🥞",
    slots: ["dinner"],
    kcal: 380,
    protein: 10,
    carbs: 62,
    fat: 8,
    tags: ["light", "veg", "south-indian"],
    ingredients: [{"name":"dosa batter","qty":150,"unit":"g","category":"grain"},{"name":"onion","qty":30,"unit":"g","category":"veg"},{"name":"tomato","qty":30,"unit":"g","category":"veg"},{"name":"oil","qty":6,"unit":"ml","category":"oil"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Vegetable Uttapam")
  },
  {
    id: "d35",
    name: "White Sauce Protein Pasta",
    emoji: "🍝",
    slots: ["dinner"],
    kcal: 610,
    protein: 26,
    carbs: 70,
    fat: 18,
    tags: ["heavy", "legume", "continental", "high-protein", "pasta"],
    ingredients: [{"name":"chickpea pasta","qty":100,"unit":"g","category":"grain"},{"name":"milk","qty":150,"unit":"ml","category":"dairy"},{"name":"cheese","qty":25,"unit":"g","category":"dairy"},{"name":"flour","qty":10,"unit":"g","category":"grain"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("White Sauce Protein Pasta")
  }
,
  {
    id: "b7",
    name: "Masala Dosa + Sambar",
    emoji: "\ud83e\uded4",
    slots: ["breakfast"],
    kcal: 420,
    protein: 11,
    carbs: 72,
    fat: 10,
    tags: ["light", "south-indian"],
    ingredients: [{"name": "dosa batter", "qty": 150, "unit": "g", "category": "grain"}, {"name": "potato masala", "qty": 100, "unit": "g", "category": "veg"}, {"name": "sambar", "qty": 150, "unit": "ml", "category": "legume"}, {"name": "oil", "qty": 8, "unit": "ml", "category": "oil"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Masala Dosa + Sambar")
  },
  {
    id: "b8",
    name: "Idli Sambar + Coconut Chutney",
    emoji: "\u26aa",
    slots: ["breakfast"],
    kcal: 340,
    protein: 12,
    carbs: 62,
    fat: 6,
    tags: ["light", "south-indian"],
    ingredients: [{"name": "idli batter", "qty": 160, "unit": "g", "category": "grain"}, {"name": "sambar", "qty": 150, "unit": "ml", "category": "legume"}, {"name": "coconut chutney", "qty": 30, "unit": "g", "category": "nut"}],
    cuisine: "south-indian",
    cookingType: "steamed",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Idli Sambar + Coconut Chutney")
  },
  {
    id: "b9",
    name: "Kanda Poha",
    emoji: "\ud83e\udd63",
    slots: ["breakfast"],
    kcal: 310,
    protein: 6,
    carbs: 54,
    fat: 8,
    tags: ["light", "poha-upma", "maharashtrian"],
    ingredients: [{"name": "flattened rice poha", "qty": 80, "unit": "g", "category": "grain"}, {"name": "onion", "qty": 50, "unit": "g", "category": "veg"}, {"name": "peanuts", "qty": 15, "unit": "g", "category": "nut"}, {"name": "oil", "qty": 8, "unit": "ml", "category": "oil"}],
    cuisine: "maharashtrian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 15,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Kanda Poha")
  },
  {
    id: "b10",
    name: "Paneer Stuffed Chilla",
    emoji: "\ud83e\udd5e",
    slots: ["breakfast"],
    kcal: 390,
    protein: 22,
    carbs: 35,
    fat: 16,
    tags: ["light", "high-protein", "paneer"],
    ingredients: [{"name": "moong dal batter", "qty": 100, "unit": "g", "category": "legume"}, {"name": "paneer", "qty": 70, "unit": "g", "category": "dairy"}, {"name": "onion", "qty": 30, "unit": "g", "category": "veg"}, {"name": "oil", "qty": 8, "unit": "ml", "category": "oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Paneer Stuffed Chilla")
  },
  {
    id: "b11",
    name: "Semolina Veg Upma",
    emoji: "\ud83e\udd63",
    slots: ["breakfast"],
    kcal: 330,
    protein: 8,
    carbs: 56,
    fat: 8,
    tags: ["light", "poha-upma", "veg", "south-indian"],
    ingredients: [{"name": "rawa semolina", "qty": 75, "unit": "g", "category": "grain"}, {"name": "carrots peas", "qty": 50, "unit": "g", "category": "veg"}, {"name": "ghee", "qty": 8, "unit": "g", "category": "dairy"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 15,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Semolina Veg Upma")
  },
  {
    id: "b12",
    name: "Paneer Bhurji Toast",
    emoji: "\ud83c\udf5e",
    slots: ["breakfast"],
    kcal: 410,
    protein: 21,
    carbs: 42,
    fat: 18,
    tags: ["light", "high-protein", "paneer", "flour"],
    ingredients: [{"name": "whole wheat bread", "qty": 80, "unit": "g", "category": "grain"}, {"name": "paneer", "qty": 80, "unit": "g", "category": "dairy"}, {"name": "butter", "qty": 10, "unit": "g", "category": "dairy"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 15,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Paneer Bhurji Toast")
  },
  {
    id: "b13",
    name: "Sabudana Wada Air Fried",
    emoji: "\ud83e\uddc6",
    slots: ["breakfast"],
    kcal: 360,
    protein: 6,
    carbs: 58,
    fat: 12,
    tags: ["light", "maharashtrian"],
    ingredients: [{"name": "sabudana", "qty": 75, "unit": "g", "category": "grain"}, {"name": "boiled potato", "qty": 60, "unit": "g", "category": "veg"}, {"name": "roasted peanuts", "qty": 25, "unit": "g", "category": "nut"}, {"name": "oil spray", "qty": 5, "unit": "ml", "category": "oil"}],
    cuisine: "maharashtrian",
    cookingType: "baked",
    equipment: ["airfryer"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Sabudana Wada Air Fried")
  },
  {
    id: "b14",
    name: "Rava Onion Dosa",
    emoji: "\ud83e\uded4",
    slots: ["breakfast"],
    kcal: 380,
    protein: 8,
    carbs: 64,
    fat: 10,
    tags: ["light", "south-indian"],
    ingredients: [{"name": "rava dosa batter", "qty": 140, "unit": "g", "category": "grain"}, {"name": "onion", "qty": 40, "unit": "g", "category": "veg"}, {"name": "oil", "qty": 10, "unit": "ml", "category": "oil"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Rava Onion Dosa")
  },
  {
    id: "b15",
    name: "Sprouted Moong Salad Bowl",
    emoji: "\ud83e\udd57",
    slots: ["breakfast"],
    kcal: 250,
    protein: 16,
    carbs: 38,
    fat: 4,
    tags: ["light", "salad"],
    ingredients: [{"name": "sprouted moong", "qty": 120, "unit": "g", "category": "legume"}, {"name": "cucumber tomato", "qty": 80, "unit": "g", "category": "veg"}, {"name": "lemon juice", "qty": 10, "unit": "ml", "category": "fruit"}],
    cuisine: "north-indian",
    cookingType: "no-cook",
    equipment: [],
    prepMinutes: 10,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Sprouted Moong Salad Bowl")
  },
  {
    id: "b16",
    name: "Puri Bhaji",
    emoji: "\ud83e\udd5f",
    slots: ["breakfast"],
    kcal: 620,
    protein: 10,
    carbs: 78,
    fat: 30,
    tags: ["fried-breakfast", "heavy", "flour"],
    ingredients: [{"name": "wheat flour", "qty": 80, "unit": "g", "category": "grain"}, {"name": "potato curry", "qty": 150, "unit": "g", "category": "veg"}, {"name": "oil for frying", "qty": 25, "unit": "ml", "category": "oil"}],
    cuisine: "north-indian",
    cookingType: "fried",
    equipment: ["stove"],
    prepMinutes: 35,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Puri Bhaji")
  },
  {
    id: "b17",
    name: "Methi Thepla + Curd",
    emoji: "\ud83e\uded3",
    slots: ["breakfast"],
    kcal: 380,
    protein: 12,
    carbs: 52,
    fat: 14,
    tags: ["light", "gujarati", "flour"],
    ingredients: [{"name": "wheat flour", "qty": 70, "unit": "g", "category": "grain"}, {"name": "fresh methi", "qty": 40, "unit": "g", "category": "veg"}, {"name": "curd", "qty": 100, "unit": "g", "category": "dairy"}, {"name": "oil", "qty": 8, "unit": "ml", "category": "oil"}],
    cuisine: "gujarati",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Methi Thepla + Curd")
  },
  {
    id: "b18",
    name: "Soya Granules Bhurji Toast",
    emoji: "\ud83c\udf5e",
    slots: ["breakfast"],
    kcal: 390,
    protein: 24,
    carbs: 45,
    fat: 12,
    tags: ["light", "high-protein", "flour", "soya"],
    ingredients: [{"name": "soya granules", "qty": 45, "unit": "g", "category": "legume"}, {"name": "whole wheat bread", "qty": 80, "unit": "g", "category": "grain"}, {"name": "onion capsicum", "qty": 50, "unit": "g", "category": "veg"}, {"name": "oil", "qty": 8, "unit": "ml", "category": "oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 15,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Soya Granules Bhurji Toast")
  },
  {
    id: "b19",
    name: "Oatmeal Apple Cinnamon Bowl",
    emoji: "\ud83e\udd63",
    slots: ["breakfast"],
    kcal: 310,
    protein: 10,
    carbs: 58,
    fat: 6,
    tags: ["light", "continental", "sweet"],
    ingredients: [{"name": "rolled oats", "qty": 50, "unit": "g", "category": "grain"}, {"name": "apple", "qty": 1, "unit": "pc", "category": "fruit"}, {"name": "milk", "qty": 150, "unit": "ml", "category": "dairy"}, {"name": "honey", "qty": 10, "unit": "g", "category": "other"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 10,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Oatmeal Apple Cinnamon Bowl")
  },
  {
    id: "b20",
    name: "Peanut Butter Banana Toast",
    emoji: "\ud83c\udf5e",
    slots: ["breakfast"],
    kcal: 370,
    protein: 13,
    carbs: 52,
    fat: 14,
    tags: ["light", "continental", "flour", "sweet"],
    ingredients: [{"name": "whole wheat bread", "qty": 80, "unit": "g", "category": "grain"}, {"name": "peanut butter", "qty": 25, "unit": "g", "category": "nut"}, {"name": "banana", "qty": 1, "unit": "pc", "category": "fruit"}],
    cuisine: "continental",
    cookingType: "no-cook",
    equipment: [],
    prepMinutes: 5,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Peanut Butter Banana Toast")
  },
  {
    id: "b21",
    name: "Set Dosa + Coconut Chutney",
    emoji: "\ud83e\udd5e",
    slots: ["breakfast"],
    kcal: 360,
    protein: 8,
    carbs: 64,
    fat: 8,
    tags: ["light", "south-indian"],
    ingredients: [{"name": "soft set dosa batter", "qty": 150, "unit": "g", "category": "grain"}, {"name": "coconut chutney", "qty": 35, "unit": "g", "category": "nut"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 15,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Set Dosa + Coconut Chutney")
  },
  {
    id: "b22",
    name: "Appam + Veg Stew",
    emoji: "\ud83e\udd5e",
    slots: ["breakfast"],
    kcal: 380,
    protein: 9,
    carbs: 62,
    fat: 11,
    tags: ["light", "veg", "south-indian"],
    ingredients: [{"name": "fermented rice batter", "qty": 130, "unit": "g", "category": "grain"}, {"name": "coconut milk veg stew", "qty": 150, "unit": "ml", "category": "veg"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Appam + Veg Stew")
  },
  {
    id: "b23",
    name: "Misal Pav",
    emoji: "\ud83c\udf72",
    slots: ["breakfast"],
    kcal: 580,
    protein: 20,
    carbs: 75,
    fat: 22,
    tags: ["maharashtrian", "legume", "high-protein", "street-food", "medium"],
    ingredients: [{"name": "sprouted moth beans curry", "qty": 150, "unit": "g", "category": "legume"}, {"name": "pav bread", "qty": 90, "unit": "g", "category": "grain"}, {"name": "farsan crunchy mix", "qty": 30, "unit": "g", "category": "grain"}],
    cuisine: "maharashtrian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 3,
    recipeUrl: youtubeSearchUrl("Misal Pav")
  },
  {
    id: "b24",
    name: "Vada Pav (2 pcs)",
    emoji: "\ud83c\udf54",
    slots: ["breakfast"],
    kcal: 540,
    protein: 12,
    carbs: 78,
    fat: 20,
    tags: ["maharashtrian", "street-food", "medium"],
    ingredients: [{"name": "batata vada", "qty": 100, "unit": "g", "category": "veg"}, {"name": "pav bread", "qty": 90, "unit": "g", "category": "grain"}, {"name": "garlic chutney", "qty": 15, "unit": "g", "category": "spice"}],
    cuisine: "maharashtrian",
    cookingType: "fried",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Vada Pav (2 pcs)")
  },
  {
    id: "b25",
    name: "Bread Pakora",
    emoji: "\ud83c\udf5e",
    slots: ["breakfast"],
    kcal: 510,
    protein: 12,
    carbs: 62,
    fat: 24,
    tags: ["fried-breakfast", "heavy", "flour"],
    ingredients: [{"name": "bread slice with potato filling", "qty": 120, "unit": "g", "category": "grain"}, {"name": "besan batter", "qty": 50, "unit": "g", "category": "legume"}, {"name": "frying oil", "qty": 20, "unit": "ml", "category": "oil"}],
    cuisine: "north-indian",
    cookingType: "fried",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Bread Pakora")
  },
  {
    id: "b26",
    name: "Radish (Mooli) Paratha",
    emoji: "\ud83e\uded3",
    slots: ["breakfast"],
    kcal: 440,
    protein: 10,
    carbs: 56,
    fat: 18,
    tags: ["paratha", "heavy", "flour"],
    ingredients: [{"name": "wheat flour", "qty": 80, "unit": "g", "category": "grain"}, {"name": "grated mooli radish", "qty": 100, "unit": "g", "category": "veg"}, {"name": "ghee", "qty": 12, "unit": "g", "category": "dairy"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Radish (Mooli) Paratha")
  },
  {
    id: "b27",
    name: "Sattu Paratha",
    emoji: "\ud83e\uded3",
    slots: ["breakfast"],
    kcal: 480,
    protein: 18,
    carbs: 64,
    fat: 16,
    tags: ["paratha", "heavy", "legume", "flour"],
    ingredients: [{"name": "wheat flour", "qty": 80, "unit": "g", "category": "grain"}, {"name": "roasted sattu gram flour", "qty": 45, "unit": "g", "category": "legume"}, {"name": "mustard oil", "qty": 10, "unit": "ml", "category": "oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 20,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Sattu Paratha")
  },
  {
    id: "b28",
    name: "Vegetable Vermicelli Upma (Sevaiya)",
    emoji: "\ud83c\udf5d",
    slots: ["breakfast"],
    kcal: 320,
    protein: 8,
    carbs: 55,
    fat: 8,
    tags: ["light", "veg", "pasta", "poha-upma"],
    ingredients: [{"name": "roasted vermicelli", "qty": 70, "unit": "g", "category": "grain"}, {"name": "carrots peas capsicum", "qty": 60, "unit": "g", "category": "veg"}, {"name": "oil", "qty": 8, "unit": "ml", "category": "oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 15,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Vegetable Vermicelli Upma (Sevaiya)")
  },
  {
    id: "b29",
    name: "Dahi Vada / Dahi Bhalla",
    emoji: "\ud83e\udd63",
    slots: ["breakfast"],
    kcal: 380,
    protein: 13,
    carbs: 48,
    fat: 14,
    tags: ["light", "legume", "street-food"],
    ingredients: [{"name": "urad dal bhalla", "qty": 100, "unit": "g", "category": "legume"}, {"name": "sweetened curd", "qty": 150, "unit": "g", "category": "dairy"}, {"name": "tamarind mint chutney", "qty": 30, "unit": "g", "category": "other"}],
    cuisine: "north-indian",
    cookingType: "fried",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Dahi Vada / Dahi Bhalla")
  },
  {
    id: "b30",
    name: "High Protein Oats Pancakes",
    emoji: "\ud83e\udd5e",
    slots: ["breakfast"],
    kcal: 360,
    protein: 22,
    carbs: 46,
    fat: 8,
    tags: ["light", "high-protein", "continental", "sweet"],
    ingredients: [{"name": "oats powder", "qty": 60, "unit": "g", "category": "grain"}, {"name": "whey protein", "qty": 20, "unit": "g", "category": "other"}, {"name": "banana milk", "qty": 100, "unit": "ml", "category": "dairy"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 15,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("High Protein Oats Pancakes")
  },
  {
    id: "l33",
    name: "Paneer Butter Masala + Jeera Rice",
    emoji: "\ud83c\udf5b",
    slots: ["lunch"],
    kcal: 710,
    protein: 25,
    carbs: 72,
    fat: 36,
    tags: ["high-protein", "heavy", "paneer", "rice"],
    ingredients: [{"name": "paneer", "qty": 120, "unit": "g", "category": "dairy"}, {"name": "basmati rice", "qty": 100, "unit": "g", "category": "grain"}, {"name": "butter cream", "qty": 25, "unit": "g", "category": "dairy"}, {"name": "tomato gravy", "qty": 100, "unit": "g", "category": "veg"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 35,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Paneer Butter Masala + Jeera Rice")
  },
  {
    id: "l34",
    name: "Dal Tadka + Jeera Rice",
    emoji: "\ud83c\udf5b",
    slots: ["lunch"],
    kcal: 540,
    protein: 18,
    carbs: 86,
    fat: 14,
    tags: ["rice", "dal", "legume", "medium"],
    ingredients: [{"name": "arhar toor dal", "qty": 70, "unit": "g", "category": "legume"}, {"name": "basmati rice", "qty": 100, "unit": "g", "category": "grain"}, {"name": "ghee", "qty": 12, "unit": "g", "category": "dairy"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["pressure-cooker"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Dal Tadka + Jeera Rice")
  },
  {
    id: "l35",
    name: "Shahi Paneer + Naan",
    emoji: "\ud83e\uded3",
    slots: ["lunch"],
    kcal: 740,
    protein: 27,
    carbs: 78,
    fat: 36,
    tags: ["high-protein", "heavy", "paneer", "flour"],
    ingredients: [{"name": "paneer", "qty": 130, "unit": "g", "category": "dairy"}, {"name": "maida naan", "qty": 100, "unit": "g", "category": "grain"}, {"name": "cashew cream paste", "qty": 30, "unit": "g", "category": "nut"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 40,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Shahi Paneer + Naan")
  },
  {
    id: "l36",
    name: "Veg Dum Biryani + Raita",
    emoji: "\ud83c\udf72",
    slots: ["lunch"],
    kcal: 620,
    protein: 16,
    carbs: 94,
    fat: 20,
    tags: ["veg", "heavy", "rice"],
    ingredients: [{"name": "basmati rice", "qty": 110, "unit": "g", "category": "grain"}, {"name": "mixed vegetables", "qty": 120, "unit": "g", "category": "veg"}, {"name": "paneer soya", "qty": 40, "unit": "g", "category": "dairy"}, {"name": "curd raita", "qty": 80, "unit": "g", "category": "dairy"}],
    cuisine: "north-indian",
    cookingType: "instant-pot",
    equipment: ["pressure-cooker"],
    prepMinutes: 45,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Veg Dum Biryani + Raita")
  },
  {
    id: "l37",
    name: "Kadhi Pakora + Steam Rice",
    emoji: "\ud83c\udf5b",
    slots: ["lunch"],
    kcal: 610,
    protein: 16,
    carbs: 88,
    fat: 22,
    tags: ["heavy", "legume", "kadhi", "rice"],
    ingredients: [{"name": "besan gram flour", "qty": 60, "unit": "g", "category": "legume"}, {"name": "sour curd", "qty": 100, "unit": "g", "category": "dairy"}, {"name": "rice", "qty": 100, "unit": "g", "category": "grain"}, {"name": "oil", "qty": 15, "unit": "ml", "category": "oil"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 40,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Kadhi Pakora + Steam Rice")
  },
  {
    id: "l38",
    name: "Gujarati Thali (Dal, Shaak, Roti, Rice)",
    emoji: "\ud83c\udf71",
    slots: ["lunch"],
    kcal: 680,
    protein: 20,
    carbs: 105,
    fat: 20,
    tags: ["heavy", "legume", "gujarati", "rice", "high-protein", "dal", "flour"],
    ingredients: [{"name": "sweet khatti dal", "qty": 100, "unit": "g", "category": "legume"}, {"name": "batata shaak", "qty": 100, "unit": "g", "category": "veg"}, {"name": "rotli", "qty": 50, "unit": "g", "category": "grain"}, {"name": "rice", "qty": 80, "unit": "g", "category": "grain"}],
    cuisine: "gujarati",
    cookingType: "stovetop",
    equipment: ["stove", "pressure-cooker"],
    prepMinutes: 45,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Gujarati Thali (Dal, Shaak, Roti, Rice)")
  },
  {
    id: "l39",
    name: "Sambar Rice + Potato Fry",
    emoji: "\ud83c\udf5b",
    slots: ["lunch"],
    kcal: 560,
    protein: 15,
    carbs: 92,
    fat: 14,
    tags: ["legume", "rice", "potato", "south-indian", "medium"],
    ingredients: [{"name": "rice", "qty": 110, "unit": "g", "category": "grain"}, {"name": "toor dal sambar", "qty": 150, "unit": "ml", "category": "legume"}, {"name": "spiced potato fry", "qty": 80, "unit": "g", "category": "veg"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["pressure-cooker"],
    prepMinutes: 35,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Sambar Rice + Potato Fry")
  },
  {
    id: "l40",
    name: "Curd Rice + Mango Pickle",
    emoji: "\ud83e\udd63",
    slots: ["lunch"],
    kcal: 420,
    protein: 11,
    carbs: 68,
    fat: 12,
    tags: ["light", "south-indian", "rice"],
    ingredients: [{"name": "cooked soft rice", "qty": 130, "unit": "g", "category": "grain"}, {"name": "fresh curd", "qty": 120, "unit": "g", "category": "dairy"}, {"name": "tadka mustard curry leaves", "qty": 10, "unit": "g", "category": "oil"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 15,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Curd Rice + Mango Pickle")
  },
  {
    id: "l41",
    name: "Paneer Lababdar + Roti",
    emoji: "\ud83e\uddc0",
    slots: ["lunch"],
    kcal: 660,
    protein: 26,
    carbs: 58,
    fat: 34,
    tags: ["high-protein", "heavy", "paneer", "flour"],
    ingredients: [{"name": "paneer", "qty": 120, "unit": "g", "category": "dairy"}, {"name": "whole wheat roti", "qty": 60, "unit": "g", "category": "grain"}, {"name": "onion tomato cashew gravy", "qty": 120, "unit": "g", "category": "veg"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 35,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Paneer Lababdar + Roti")
  },
  {
    id: "l42",
    name: "Matar Paneer + Roti",
    emoji: "\ud83e\udedb",
    slots: ["lunch"],
    kcal: 590,
    protein: 24,
    carbs: 60,
    fat: 26,
    tags: ["veg", "paneer", "high-protein", "flour", "medium"],
    ingredients: [{"name": "paneer", "qty": 100, "unit": "g", "category": "dairy"}, {"name": "green peas", "qty": 80, "unit": "g", "category": "veg"}, {"name": "wheat roti", "qty": 60, "unit": "g", "category": "grain"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Matar Paneer + Roti")
  },
  {
    id: "l43",
    name: "Malai Kofta + Roti",
    emoji: "\ud83e\uddc6",
    slots: ["lunch"],
    kcal: 720,
    protein: 18,
    carbs: 68,
    fat: 42,
    tags: ["heavy", "flour"],
    ingredients: [{"name": "paneer potato kofta", "qty": 120, "unit": "g", "category": "dairy"}, {"name": "rich creamy gravy", "qty": 100, "unit": "g", "category": "dairy"}, {"name": "roti", "qty": 60, "unit": "g", "category": "grain"}],
    cuisine: "punjabi",
    cookingType: "fried",
    equipment: ["stove"],
    prepMinutes: 45,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Malai Kofta + Roti")
  },
  {
    id: "l44",
    name: "Pithla Bhakri",
    emoji: "\ud83e\uded3",
    slots: ["lunch"],
    kcal: 510,
    protein: 17,
    carbs: 76,
    fat: 14,
    tags: ["maharashtrian", "legume", "medium"],
    ingredients: [{"name": "besan pitla", "qty": 120, "unit": "g", "category": "legume"}, {"name": "jowar bhakri", "qty": 80, "unit": "g", "category": "grain"}, {"name": "thecha chilli garlic paste", "qty": 15, "unit": "g", "category": "spice"}],
    cuisine: "maharashtrian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 25,
    spiceLevel: 3,
    recipeUrl: youtubeSearchUrl("Pithla Bhakri")
  },
  {
    id: "l45",
    name: "Baingan Bharta + Missi Roti",
    emoji: "\ud83c\udf46",
    slots: ["lunch"],
    kcal: 520,
    protein: 16,
    carbs: 68,
    fat: 18,
    tags: ["veg", "flour", "medium"],
    ingredients: [{"name": "roasted eggplant bharta", "qty": 180, "unit": "g", "category": "veg"}, {"name": "missi roti besan wheat", "qty": 80, "unit": "g", "category": "grain"}, {"name": "mustard oil", "qty": 10, "unit": "ml", "category": "oil"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 35,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Baingan Bharta + Missi Roti")
  },
  {
    id: "l46",
    name: "Kashmiri Dum Aloo + Rice",
    emoji: "\ud83e\udd54",
    slots: ["lunch"],
    kcal: 610,
    protein: 12,
    carbs: 85,
    fat: 24,
    tags: ["heavy", "potato", "rice"],
    ingredients: [{"name": "baby potatoes", "qty": 150, "unit": "g", "category": "veg"}, {"name": "spiced curd gravy", "qty": 100, "unit": "g", "category": "dairy"}, {"name": "basmati rice", "qty": 100, "unit": "g", "category": "grain"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 40,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Kashmiri Dum Aloo + Rice")
  },
  {
    id: "l47",
    name: "Chana Dal + Lauki + Roti",
    emoji: "\ud83c\udf72",
    slots: ["lunch"],
    kcal: 490,
    protein: 18,
    carbs: 74,
    fat: 12,
    tags: ["legume", "chana-rajma", "veg", "dal", "flour", "medium"],
    ingredients: [{"name": "chana dal bottle gourd", "qty": 180, "unit": "g", "category": "legume"}, {"name": "wheat roti", "qty": 60, "unit": "g", "category": "grain"}, {"name": "ghee tadka", "qty": 8, "unit": "g", "category": "dairy"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["pressure-cooker"],
    prepMinutes: 30,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Chana Dal + Lauki + Roti")
  },
  {
    id: "l48",
    name: "Soya Chunk Curry + Rice",
    emoji: "\ud83c\udf5b",
    slots: ["lunch"],
    kcal: 560,
    protein: 30,
    carbs: 82,
    fat: 12,
    tags: ["legume", "rice", "high-protein", "soya", "medium"],
    ingredients: [{"name": "soya chunks", "qty": 60, "unit": "g", "category": "legume"}, {"name": "tomato onion curry", "qty": 100, "unit": "g", "category": "veg"}, {"name": "rice", "qty": 100, "unit": "g", "category": "grain"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Soya Chunk Curry + Rice")
  },
  {
    id: "l49",
    name: "Chana Masala + Poori",
    emoji: "\ud83e\udd5f",
    slots: ["lunch"],
    kcal: 640,
    protein: 19,
    carbs: 82,
    fat: 26,
    tags: ["heavy", "legume", "flour", "chana-rajma"],
    ingredients: [{"name": "spiced kabuli chana", "qty": 100, "unit": "g", "category": "legume"}, {"name": "wheat poori", "qty": 80, "unit": "g", "category": "grain"}, {"name": "oil", "qty": 20, "unit": "ml", "category": "oil"}],
    cuisine: "punjabi",
    cookingType: "fried",
    equipment: ["stove"],
    prepMinutes: 40,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Chana Masala + Poori")
  },
  {
    id: "l50",
    name: "Bisi Bele Bath + Boondi Raita",
    emoji: "\ud83c\udf5b",
    slots: ["lunch"],
    kcal: 530,
    protein: 14,
    carbs: 84,
    fat: 15,
    tags: ["legume", "rice", "dal", "south-indian", "medium"],
    ingredients: [{"name": "rice lentil tamarind mash", "qty": 150, "unit": "g", "category": "grain"}, {"name": "mixed vegetables", "qty": 60, "unit": "g", "category": "veg"}, {"name": "ghee tadka", "qty": 12, "unit": "g", "category": "dairy"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["pressure-cooker"],
    prepMinutes: 35,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Bisi Bele Bath + Boondi Raita")
  },
  {
    id: "l51",
    name: "Tofu Kadhai Masala + Roti",
    emoji: "\ud83e\udd57",
    slots: ["lunch"],
    kcal: 510,
    protein: 26,
    carbs: 54,
    fat: 20,
    tags: ["legume", "soya", "high-protein", "flour", "medium"],
    ingredients: [{"name": "firm tofu", "qty": 120, "unit": "g", "category": "legume"}, {"name": "capsicum onion tomato", "qty": 100, "unit": "g", "category": "veg"}, {"name": "roti", "qty": 60, "unit": "g", "category": "grain"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Tofu Kadhai Masala + Roti")
  },
  {
    id: "l52",
    name: "Navratan Korma + Lachha Paratha",
    emoji: "\ud83e\uded3",
    slots: ["lunch"],
    kcal: 730,
    protein: 18,
    carbs: 78,
    fat: 38,
    tags: ["paratha", "heavy", "flour"],
    ingredients: [{"name": "mixed vegetables nuts fruits", "qty": 150, "unit": "g", "category": "veg"}, {"name": "creamy korma gravy", "qty": 100, "unit": "g", "category": "dairy"}, {"name": "lachha paratha", "qty": 90, "unit": "g", "category": "grain"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 45,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Navratan Korma + Lachha Paratha")
  },
  {
    id: "l53",
    name: "Kathal Jackfruit Masala + Roti",
    emoji: "\ud83c\udf5b",
    slots: ["lunch"],
    kcal: 490,
    protein: 12,
    carbs: 64,
    fat: 18,
    tags: ["veg", "flour", "medium"],
    ingredients: [{"name": "tender raw jackfruit kathal", "qty": 150, "unit": "g", "category": "veg"}, {"name": "spiced onion curry", "qty": 100, "unit": "g", "category": "veg"}, {"name": "wheat roti", "qty": 60, "unit": "g", "category": "grain"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 40,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Kathal Jackfruit Masala + Roti")
  },
  {
    id: "l54",
    name: "Bhindi Do Pyaza + Roti",
    emoji: "\ud83c\udf3f",
    slots: ["lunch"],
    kcal: 460,
    protein: 11,
    carbs: 58,
    fat: 16,
    tags: ["veg", "flour", "medium"],
    ingredients: [{"name": "fresh okra bhindi", "qty": 120, "unit": "g", "category": "veg"}, {"name": "cubed onions", "qty": 80, "unit": "g", "category": "veg"}, {"name": "roti", "qty": 60, "unit": "g", "category": "grain"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Bhindi Do Pyaza + Roti")
  },
  {
    id: "l55",
    name: "Corn Spinach Palak Corn + Roti",
    emoji: "\ud83c\udf3d",
    slots: ["lunch"],
    kcal: 480,
    protein: 14,
    carbs: 60,
    fat: 18,
    tags: ["leafy", "veg", "flour", "medium"],
    ingredients: [{"name": "spinach palak puree", "qty": 150, "unit": "g", "category": "veg"}, {"name": "sweet corn kernels", "qty": 60, "unit": "g", "category": "veg"}, {"name": "roti", "qty": 60, "unit": "g", "category": "grain"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Corn Spinach Palak Corn + Roti")
  },
  {
    id: "l56",
    name: "Jeera Aloo + Dal Fry + Roti",
    emoji: "\ud83e\udd54",
    slots: ["lunch"],
    kcal: 560,
    protein: 17,
    carbs: 78,
    fat: 18,
    tags: ["legume", "potato", "dal", "flour", "medium"],
    ingredients: [{"name": "boiled potatoes with cumin", "qty": 120, "unit": "g", "category": "veg"}, {"name": "yellow dal fry", "qty": 120, "unit": "g", "category": "legume"}, {"name": "roti", "qty": 60, "unit": "g", "category": "grain"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Jeera Aloo + Dal Fry + Roti")
  },
  {
    id: "l57",
    name: "Paneer Do Pyaza + Jeera Rice",
    emoji: "\ud83e\uddc0",
    slots: ["lunch"],
    kcal: 670,
    protein: 25,
    carbs: 70,
    fat: 32,
    tags: ["high-protein", "heavy", "paneer", "rice"],
    ingredients: [{"name": "paneer", "qty": 120, "unit": "g", "category": "dairy"}, {"name": "double onions gravy", "qty": 100, "unit": "g", "category": "veg"}, {"name": "jeera rice", "qty": 100, "unit": "g", "category": "grain"}],
    cuisine: "punjabi",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 30,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Paneer Do Pyaza + Jeera Rice")
  },
  {
    id: "l58",
    name: "Soy Bean Curry + Roti",
    emoji: "\ud83e\udedb",
    slots: ["lunch"],
    kcal: 520,
    protein: 28,
    carbs: 60,
    fat: 14,
    tags: ["high-protein", "legume", "flour", "medium"],
    ingredients: [{"name": "whole soybean seeds soaked", "qty": 70, "unit": "g", "category": "legume"}, {"name": "curry gravy", "qty": 100, "unit": "g", "category": "veg"}, {"name": "roti", "qty": 60, "unit": "g", "category": "grain"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["pressure-cooker"],
    prepMinutes: 35,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Soy Bean Curry + Roti")
  },
  {
    id: "l59",
    name: "Veg Pulao + Boondi Raita",
    emoji: "\ud83c\udf5a",
    slots: ["lunch"],
    kcal: 490,
    protein: 12,
    carbs: 76,
    fat: 14,
    tags: ["rice", "veg", "medium"],
    ingredients: [{"name": "basmati rice", "qty": 100, "unit": "g", "category": "grain"}, {"name": "veggies peas carrots", "qty": 80, "unit": "g", "category": "veg"}, {"name": "curd boondi raita", "qty": 100, "unit": "g", "category": "dairy"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Veg Pulao + Boondi Raita")
  },
  {
    id: "l60",
    name: "Vangi Bath Eggplant Rice",
    emoji: "\ud83c\udf46",
    slots: ["lunch"],
    kcal: 470,
    protein: 9,
    carbs: 74,
    fat: 14,
    tags: ["rice", "maharashtrian", "medium"],
    ingredients: [{"name": "rice", "qty": 100, "unit": "g", "category": "grain"}, {"name": "brinjal eggplant slices", "qty": 100, "unit": "g", "category": "veg"}, {"name": "vangi bath masala ghee", "qty": 15, "unit": "g", "category": "spice"}],
    cuisine: "maharashtrian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Vangi Bath Eggplant Rice")
  },
  {
    id: "d36",
    name: "Masala Khichdi + Papad",
    emoji: "\ud83c\udf72",
    slots: ["dinner"],
    kcal: 420,
    protein: 14,
    carbs: 68,
    fat: 10,
    tags: ["legume", "gujarati", "rice", "light", "khichdi", "dal"],
    ingredients: [{"name": "rice moong dal", "qty": 100, "unit": "g", "category": "grain"}, {"name": "mixed veg", "qty": 60, "unit": "g", "category": "veg"}, {"name": "ghee", "qty": 10, "unit": "g", "category": "dairy"}],
    cuisine: "gujarati",
    cookingType: "stovetop",
    equipment: ["pressure-cooker"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Masala Khichdi + Papad")
  },
  {
    id: "d37",
    name: "Plain Dosa + Coconut Chutney",
    emoji: "\ud83e\uded4",
    slots: ["dinner"],
    kcal: 360,
    protein: 8,
    carbs: 60,
    fat: 9,
    tags: ["light", "south-indian"],
    ingredients: [{"name": "dosa batter", "qty": 140, "unit": "g", "category": "grain"}, {"name": "coconut chutney", "qty": 30, "unit": "g", "category": "nut"}, {"name": "oil", "qty": 6, "unit": "ml", "category": "oil"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 15,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Plain Dosa + Coconut Chutney")
  },
  {
    id: "d38",
    name: "Soya Tikka Roll",
    emoji: "\ud83c\udf2f",
    slots: ["dinner"],
    kcal: 460,
    protein: 24,
    carbs: 52,
    fat: 16,
    tags: ["legume", "soya", "high-protein", "flour", "medium"],
    ingredients: [{"name": "whole wheat wrap", "qty": 70, "unit": "g", "category": "grain"}, {"name": "grilled soya tikka", "qty": 80, "unit": "g", "category": "legume"}, {"name": "mint chutney veg", "qty": 30, "unit": "g", "category": "veg"}],
    cuisine: "north-indian",
    cookingType: "grilled",
    equipment: ["griddle"],
    prepMinutes: 20,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Soya Tikka Roll")
  },
  {
    id: "d39",
    name: "Paneer Tikka Roll",
    emoji: "\ud83c\udf2f",
    slots: ["dinner"],
    kcal: 490,
    protein: 23,
    carbs: 48,
    fat: 22,
    tags: ["high-protein", "paneer", "flour", "medium"],
    ingredients: [{"name": "roti wrap", "qty": 60, "unit": "g", "category": "grain"}, {"name": "paneer tikka", "qty": 90, "unit": "g", "category": "dairy"}, {"name": "onion peppers", "qty": 40, "unit": "g", "category": "veg"}],
    cuisine: "punjabi",
    cookingType: "grilled",
    equipment: ["griddle"],
    prepMinutes: 20,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Paneer Tikka Roll")
  },
  {
    id: "d40",
    name: "Palak Soup + Garlic Toast",
    emoji: "\ud83e\udd63",
    slots: ["dinner"],
    kcal: 310,
    protein: 10,
    carbs: 42,
    fat: 11,
    tags: ["soup", "continental", "light", "leafy", "flour"],
    ingredients: [{"name": "fresh spinach", "qty": 150, "unit": "g", "category": "veg"}, {"name": "garlic bread slice", "qty": 60, "unit": "g", "category": "grain"}, {"name": "butter", "qty": 8, "unit": "g", "category": "dairy"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove", "blender"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Palak Soup + Garlic Toast")
  },
  {
    id: "d41",
    name: "Veg Noodles Hakka Style",
    emoji: "\ud83c\udf5c",
    slots: ["dinner"],
    kcal: 480,
    protein: 11,
    carbs: 76,
    fat: 14,
    tags: ["veg", "pasta", "indo-chinese", "medium"],
    ingredients: [{"name": "hakka noodles", "qty": 90, "unit": "g", "category": "grain"}, {"name": "shredded cabbage carrots", "qty": 100, "unit": "g", "category": "veg"}, {"name": "soy chilli sauce", "qty": 15, "unit": "ml", "category": "spice"}],
    cuisine: "indo-chinese",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Veg Noodles Hakka Style")
  },
  {
    id: "d42",
    name: "Corn & Cheese Grilled Sandwich",
    emoji: "\ud83e\udd6a",
    slots: ["dinner"],
    kcal: 450,
    protein: 14,
    carbs: 54,
    fat: 18,
    tags: ["light", "veg", "continental"],
    ingredients: [{"name": "bread slices", "qty": 80, "unit": "g", "category": "grain"}, {"name": "sweet corn", "qty": 50, "unit": "g", "category": "veg"}, {"name": "mozzarella cheese", "qty": 30, "unit": "g", "category": "dairy"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 15,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Corn & Cheese Grilled Sandwich")
  },
  {
    id: "d43",
    name: "Lauki Chana Dal + Roti",
    emoji: "\ud83c\udf72",
    slots: ["dinner"],
    kcal: 410,
    protein: 15,
    carbs: 62,
    fat: 10,
    tags: ["legume", "chana-rajma", "veg", "light", "dal", "flour"],
    ingredients: [{"name": "bottle gourd chana dal", "qty": 160, "unit": "g", "category": "legume"}, {"name": "wheat roti", "qty": 50, "unit": "g", "category": "grain"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["pressure-cooker"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Lauki Chana Dal + Roti")
  },
  {
    id: "d44",
    name: "Crispy Tofu Stir-Fry + Brown Rice",
    emoji: "\ud83e\udd57",
    slots: ["dinner"],
    kcal: 430,
    protein: 22,
    carbs: 55,
    fat: 13,
    tags: ["legume", "rice", "indo-chinese", "light", "high-protein", "soya"],
    ingredients: [{"name": "firm tofu", "qty": 100, "unit": "g", "category": "legume"}, {"name": "bell peppers broccoli", "qty": 100, "unit": "g", "category": "veg"}, {"name": "brown rice", "qty": 80, "unit": "g", "category": "grain"}],
    cuisine: "indo-chinese",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Crispy Tofu Stir-Fry + Brown Rice")
  },
  {
    id: "d45",
    name: "South Indian Lemon Rice",
    emoji: "\ud83c\udf4b",
    slots: ["dinner"],
    kcal: 410,
    protein: 7,
    carbs: 68,
    fat: 11,
    tags: ["light", "south-indian", "rice"],
    ingredients: [{"name": "basmati rice", "qty": 90, "unit": "g", "category": "grain"}, {"name": "lemon juice peanuts", "qty": 25, "unit": "g", "category": "nut"}, {"name": "tadka spices", "qty": 10, "unit": "g", "category": "spice"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 15,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("South Indian Lemon Rice")
  },
  {
    id: "d46",
    name: "Methi Oats Chilla",
    emoji: "\ud83e\udd5e",
    slots: ["dinner"],
    kcal: 320,
    protein: 12,
    carbs: 48,
    fat: 8,
    tags: ["light", "leafy", "legume"],
    ingredients: [{"name": "oats flour", "qty": 60, "unit": "g", "category": "grain"}, {"name": "besan", "qty": 20, "unit": "g", "category": "legume"}, {"name": "chopped methi", "qty": 40, "unit": "g", "category": "veg"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 15,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Methi Oats Chilla")
  },
  {
    id: "d47",
    name: "Tofu Bhurji + Roti",
    emoji: "\ud83e\udd57",
    slots: ["dinner"],
    kcal: 420,
    protein: 25,
    carbs: 45,
    fat: 14,
    tags: ["legume", "soya", "light", "high-protein", "flour"],
    ingredients: [{"name": "tofu", "qty": 130, "unit": "g", "category": "legume"}, {"name": "onion tomato", "qty": 60, "unit": "g", "category": "veg"}, {"name": "roti", "qty": 50, "unit": "g", "category": "grain"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Tofu Bhurji + Roti")
  },
  {
    id: "d48",
    name: "Rava Onion Uttapam",
    emoji: "\ud83e\udd5e",
    slots: ["dinner"],
    kcal: 370,
    protein: 9,
    carbs: 62,
    fat: 9,
    tags: ["light", "south-indian"],
    ingredients: [{"name": "rava batter", "qty": 130, "unit": "g", "category": "grain"}, {"name": "finely chopped onions", "qty": 40, "unit": "g", "category": "veg"}, {"name": "oil", "qty": 8, "unit": "ml", "category": "oil"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Rava Onion Uttapam")
  },
  {
    id: "d49",
    name: "Mixed Veg Soup + Baked Croutons",
    emoji: "\ud83e\udd63",
    slots: ["dinner"],
    kcal: 280,
    protein: 7,
    carbs: 42,
    fat: 8,
    tags: ["light", "veg", "continental", "soup"],
    ingredients: [{"name": "carrots beans corn", "qty": 150, "unit": "g", "category": "veg"}, {"name": "bread croutons", "qty": 30, "unit": "g", "category": "grain"}, {"name": "olive oil", "qty": 6, "unit": "ml", "category": "oil"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Mixed Veg Soup + Baked Croutons")
  },
  {
    id: "d50",
    name: "Quinoa Veg Pulao",
    emoji: "\ud83c\udf5a",
    slots: ["dinner"],
    kcal: 390,
    protein: 14,
    carbs: 58,
    fat: 10,
    tags: ["light", "veg", "continental", "rice"],
    ingredients: [{"name": "quinoa", "qty": 75, "unit": "g", "category": "grain"}, {"name": "mixed vegetables", "qty": 80, "unit": "g", "category": "veg"}, {"name": "ghee", "qty": 8, "unit": "g", "category": "dairy"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Quinoa Veg Pulao")
  },
  {
    id: "d51",
    name: "Vegetable Manchow Soup + Fried Noodles",
    emoji: "\ud83e\udd63",
    slots: ["dinner"],
    kcal: 310,
    protein: 8,
    carbs: 46,
    fat: 10,
    tags: ["soup", "indo-chinese", "veg", "light", "pasta"],
    ingredients: [{"name": "mixed soup veg", "qty": 150, "unit": "g", "category": "veg"}, {"name": "fried noodles", "qty": 30, "unit": "g", "category": "grain"}, {"name": "chilli soy garlic", "qty": 10, "unit": "g", "category": "spice"}],
    cuisine: "indo-chinese",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Vegetable Manchow Soup + Fried Noodles")
  },
  {
    id: "d52",
    name: "Hot & Sour Veg Soup",
    emoji: "\ud83e\udd63",
    slots: ["dinner"],
    kcal: 260,
    protein: 7,
    carbs: 38,
    fat: 8,
    tags: ["light", "veg", "soup", "indo-chinese"],
    ingredients: [{"name": "mushrooms cabbage tofu", "qty": 120, "unit": "g", "category": "veg"}, {"name": "vinegar pepper sauce", "qty": 15, "unit": "ml", "category": "spice"}],
    cuisine: "indo-chinese",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 15,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Hot & Sour Veg Soup")
  },
  {
    id: "d53",
    name: "Avocado Toast with Seeds",
    emoji: "\ud83c\udf5e",
    slots: ["dinner"],
    kcal: 380,
    protein: 11,
    carbs: 40,
    fat: 18,
    tags: ["light", "continental", "flour"],
    ingredients: [{"name": "whole grain sourdough bread", "qty": 80, "unit": "g", "category": "grain"}, {"name": "mashed avocado", "qty": 70, "unit": "g", "category": "veg"}, {"name": "pumpkin flax seeds", "qty": 15, "unit": "g", "category": "nut"}],
    cuisine: "continental",
    cookingType: "no-cook",
    equipment: [],
    prepMinutes: 10,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Avocado Toast with Seeds")
  },
  {
    id: "d54",
    name: "Grilled Cottage Cheese Salad",
    emoji: "\ud83e\udd57",
    slots: ["dinner"],
    kcal: 360,
    protein: 24,
    carbs: 18,
    fat: 20,
    tags: ["light", "high-protein", "salad", "continental"],
    ingredients: [{"name": "paneer cottage cheese cubes", "qty": 120, "unit": "g", "category": "dairy"}, {"name": "bell peppers lettuce", "qty": 120, "unit": "g", "category": "veg"}, {"name": "olive oil lemon dressing", "qty": 15, "unit": "ml", "category": "oil"}],
    cuisine: "continental",
    cookingType: "grilled",
    equipment: ["griddle"],
    prepMinutes: 15,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Grilled Cottage Cheese Salad")
  },
  {
    id: "d55",
    name: "Chana Chatpata Salad",
    emoji: "\ud83e\udd57",
    slots: ["dinner"],
    kcal: 330,
    protein: 16,
    carbs: 48,
    fat: 6,
    tags: ["light", "legume", "salad", "chana-rajma"],
    ingredients: [{"name": "boiled kabuli chana", "qty": 120, "unit": "g", "category": "legume"}, {"name": "onion tomato cucumber", "qty": 80, "unit": "g", "category": "veg"}, {"name": "chaat masala lemon", "qty": 10, "unit": "g", "category": "spice"}],
    cuisine: "north-indian",
    cookingType: "no-cook",
    equipment: [],
    prepMinutes: 10,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Chana Chatpata Salad")
  },
  {
    id: "d56",
    name: "Veg Kathi Roll",
    emoji: "\ud83c\udf2f",
    slots: ["dinner"],
    kcal: 440,
    protein: 13,
    carbs: 58,
    fat: 16,
    tags: ["light", "veg", "street-food", "flour"],
    ingredients: [{"name": "roti wrap", "qty": 60, "unit": "g", "category": "grain"}, {"name": "mixed veg potato stuffing", "qty": 100, "unit": "g", "category": "veg"}, {"name": "mint sauce", "qty": 20, "unit": "g", "category": "spice"}],
    cuisine: "north-indian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 20,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Veg Kathi Roll")
  },
  {
    id: "d57",
    name: "Spaghetti Aglio e Olio",
    emoji: "\ud83c\udf5d",
    slots: ["dinner"],
    kcal: 490,
    protein: 12,
    carbs: 72,
    fat: 16,
    tags: ["pasta", "continental", "medium"],
    ingredients: [{"name": "spaghetti pasta", "qty": 90, "unit": "g", "category": "grain"}, {"name": "extra virgin olive oil", "qty": 18, "unit": "ml", "category": "oil"}, {"name": "sliced garlic chilli flakes", "qty": 10, "unit": "g", "category": "spice"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 2,
    recipeUrl: youtubeSearchUrl("Spaghetti Aglio e Olio")
  },
  {
    id: "d58",
    name: "Curd Sewaiya Dahi Sevai",
    emoji: "\ud83e\udd63",
    slots: ["dinner"],
    kcal: 340,
    protein: 10,
    carbs: 54,
    fat: 8,
    tags: ["light", "south-indian"],
    ingredients: [{"name": "roasted vermicelli", "qty": 70, "unit": "g", "category": "grain"}, {"name": "fresh curd yogurt", "qty": 120, "unit": "g", "category": "dairy"}, {"name": "curry leaves mustard tadka", "qty": 8, "unit": "g", "category": "oil"}],
    cuisine: "south-indian",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 15,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Curd Sewaiya Dahi Sevai")
  },
  {
    id: "d59",
    name: "Sabudana Thalipeeth",
    emoji: "\ud83e\udd5e",
    slots: ["dinner"],
    kcal: 410,
    protein: 7,
    carbs: 64,
    fat: 14,
    tags: ["light", "maharashtrian"],
    ingredients: [{"name": "soaked sabudana", "qty": 80, "unit": "g", "category": "grain"}, {"name": "mashed potato peanut flour", "qty": 80, "unit": "g", "category": "veg"}, {"name": "oil", "qty": 10, "unit": "ml", "category": "oil"}],
    cuisine: "maharashtrian",
    cookingType: "stovetop",
    equipment: ["griddle"],
    prepMinutes: 25,
    spiceLevel: 1,
    recipeUrl: youtubeSearchUrl("Sabudana Thalipeeth")
  },
  {
    id: "d60",
    name: "Tomato Basil Pasta Soup",
    emoji: "\ud83e\udd63",
    slots: ["dinner"],
    kcal: 330,
    protein: 10,
    carbs: 52,
    fat: 8,
    tags: ["light", "pasta", "continental", "soup"],
    ingredients: [{"name": "ripe tomatoes puree", "qty": 150, "unit": "g", "category": "veg"}, {"name": "small pasta macaroni", "qty": 40, "unit": "g", "category": "grain"}, {"name": "olive oil basil leaves", "qty": 8, "unit": "ml", "category": "oil"}],
    cuisine: "continental",
    cookingType: "stovetop",
    equipment: ["stove"],
    prepMinutes: 20,
    spiceLevel: 0,
    recipeUrl: youtubeSearchUrl("Tomato Basil Pasta Soup")
  }
];

export const DISHES_BY_ID: Record<string, Dish> = Object.fromEntries(DISHES.map((d) => [d.id, d]));

export function dishesForSlot(slot: Slot): Dish[] {
  return DISHES.filter((d) => d.slots.includes(slot));
}
