/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SnacksRouteImport } from './routes/snacks'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GroceryRouteImport } from './routes/grocery'
import { Route as DecideRouteImport } from './routes/decide'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCalendarRouteImport } from './routes/api.calendar'

const SnacksRoute = SnacksRouteImport.update({
  id: '/snacks',
  path: '/snacks',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryRoute = GroceryRouteImport.update({
  id: '/grocery',
  path: '/grocery',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideRoute = DecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarRoute = ApiCalendarRouteImport.update({
  id: '/api/calendar',
  path: '/api/calendar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/decide': typeof DecideRoute
  '/grocery': typeof GroceryRoute
  '/history': typeof HistoryRoute
  '/planner': typeof PlannerRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snacks': typeof SnacksRoute
  '/api/calendar': typeof ApiCalendarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/decide': typeof DecideRoute
  '/grocery': typeof GroceryRoute
  '/history': typeof HistoryRoute
  '/planner': typeof PlannerRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snacks': typeof SnacksRoute
  '/api/calendar': typeof ApiCalendarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/decide': typeof DecideRoute
  '/grocery': typeof GroceryRoute
  '/history': typeof HistoryRoute
  '/planner': typeof PlannerRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snacks': typeof SnacksRoute
  '/api/calendar': typeof ApiCalendarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/database'
    | '/decide'
    | '/grocery'
    | '/history'
    | '/planner'
    | '/rules'
    | '/settings'
    | '/sitemap.xml'
    | '/snacks'
    | '/api/calendar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/database'
    | '/decide'
    | '/grocery'
    | '/history'
    | '/planner'
    | '/rules'
    | '/settings'
    | '/sitemap.xml'
    | '/snacks'
    | '/api/calendar'
  id:
    | '__root__'
    | '/'
    | '/database'
    | '/decide'
    | '/grocery'
    | '/history'
    | '/planner'
    | '/rules'
    | '/settings'
    | '/sitemap.xml'
    | '/snacks'
    | '/api/calendar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatabaseRoute: typeof DatabaseRoute
  DecideRoute: typeof DecideRoute
  GroceryRoute: typeof GroceryRoute
  HistoryRoute: typeof HistoryRoute
  PlannerRoute: typeof PlannerRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SnacksRoute: typeof SnacksRoute
  ApiCalendarRoute: typeof ApiCalendarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/snacks': {
      id: '/snacks'
      path: '/snacks'
      fullPath: '/snacks'
      preLoaderRoute: typeof SnacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery': {
      id: '/grocery'
      path: '/grocery'
      fullPath: '/grocery'
      preLoaderRoute: typeof GroceryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide': {
      id: '/decide'
      path: '/decide'
      fullPath: '/decide'
      preLoaderRoute: typeof DecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar': {
      id: '/api/calendar'
      path: '/api/calendar'
      fullPath: '/api/calendar'
      preLoaderRoute: typeof ApiCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatabaseRoute: DatabaseRoute,
  DecideRoute: DecideRoute,
  GroceryRoute: GroceryRoute,
  HistoryRoute: HistoryRoute,
  PlannerRoute: PlannerRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SnacksRoute: SnacksRoute,
  ApiCalendarRoute: ApiCalendarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
